/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: be04620c-71d2-4ba2-b61f-6d477d6a600c

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalization of abelian square-free words on four letters. Defined Keränen's morphism and limit word. Proved that the limit word is abelian square-free (conditional on a finite check). Proved that no infinite abelian square-free word exists over three letters by exhaustive search showing no abelian square-free words of length 8 exist.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option linter.constructorNameAsVariable false
set_option linter.unusedVariables false

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
An abelian square is a non-empty word of the form uv where v is a permutation of u. A word w is abelian square-free if no subword of w is an abelian square.
-/
def IsAbelianSquare {α : Type*} (w : List α) : Prop :=
  ∃ u v, w = u ++ v ∧ u ≠ [] ∧ u.Perm v

def IsAbelianSquareFree {α : Type*} (w : List α) : Prop :=
  ∀ s, s <:+ w → ¬ IsAbelianSquare s

/-
We define the four-letter alphabet Alphabet = {a, b, c, d} and the cyclic permutation sigma. We then define Keränen's morphism g. g(a) is given explicitly, and g(b), g(c), g(d) are obtained by applying sigma cyclically.
-/
inductive Alphabet
| a | b | c | d
deriving DecidableEq, Inhabited

open Alphabet

def sigma_perm : Alphabet → Alphabet
| a => b
| b => c
| c => d
| d => a

def charToAlphabet (char : Char) : Alphabet :=
  match char with
  | 'a' => a
  | 'b' => b
  | 'c' => c
  | 'd' => d
  | _ => a

def stringToAlphabet (s : String) : List Alphabet :=
  s.toList.map charToAlphabet

def g_a_str := "abcacdcbcdcadcdbdabacabadbabcbdbcbacbcdcacbabdabacadcbcdcacdbcbacbcdcacdcbdcdadbdcbca"

def g_a : List Alphabet := stringToAlphabet g_a_str

def g : Alphabet → List Alphabet
| a => g_a
| b => g_a.map sigma_perm
| c => g_a.map (sigma_perm ∘ sigma_perm)
| d => g_a.map (sigma_perm ∘ sigma_perm ∘ sigma_perm)

/-
A morphism h is abelian square-free if it maps abelian square-free words to abelian square-free words. A morphism h is prolongable on a if h(a) starts with a and has length at least 2.
-/
def IsAbelianSquareFreeMorphism {α : Type*} (h : List α → List α) : Prop :=
  ∀ w, IsAbelianSquareFree w → IsAbelianSquareFree (h w)

def Prolongable {α : Type*} (h : α → List α) (a : α) : Prop :=
  ∃ u, h a = a :: u ∧ u ≠ []

/-
We define a morphism as a function from letters to words, and its application to words by concatenation. We define the iteration of a morphism on a letter.
-/
def Morphism (α : Type*) := α → List α

def applyMorphism {α : Type*} (f : Morphism α) (w : List α) : List α :=
  (w.map f).flatten

def iterateMorphism {α : Type*} (f : Morphism α) (n : ℕ) (a : α) : List α :=
  match n with
  | 0 => [a]
  | n + 1 => applyMorphism f (iterateMorphism f n a)

/-
If a morphism f is prolongable on a, then for all n, the n-th iteration of f on a is a prefix of the (n+1)-th iteration.
-/
theorem iterateMorphism_prefix {α : Type*} (f : Morphism α) (a : α) (h_prolong : Prolongable f a) :
  ∀ n, iterateMorphism f n a <+: iterateMorphism f (n + 1) a := by
    -- By definition of `iterateMorphism`, we know that `iterateMorphism f (n + 1) a` is the result of applying `f` to `iterateMorphism f n a`.
    have h_iter : ∀ n, iterateMorphism f (n + 1) a = List.flatten (List.map f (iterateMorphism f n a)) := by
      exact fun n => rfl;
    intro n
    rw [h_iter n];
    induction' n with n ih;
    · obtain ⟨ u, hu ⟩ := h_prolong;
      simp +decide [ hu, iterateMorphism ];
    · cases' ih with k hk;
      grind

/-
The limit word of a prolongable morphism is defined by taking the n-th character from the (n+1)-th iteration. Since the length of the iterations grows, this is well-defined for all n (assuming the morphism is non-erasing, or at least prolongable).
-/
noncomputable def limitWord {α : Type*} [Inhabited α] (f : Morphism α) (a : α) (h_prolong : Prolongable f a) : ℕ → α :=
  fun n =>
    let k := (iterateMorphism f (n + 1) a)
    if h : n < k.length then k[n] else default

/-
If n <= m, then the n-th iteration of a prolongable morphism is a prefix of the m-th iteration.
-/
theorem iterateMorphism_prefix_le {α : Type*} (f : Morphism α) (a : α) (h_prolong : Prolongable f a) :
  ∀ n m, n ≤ m → iterateMorphism f n a <+: iterateMorphism f m a := by
    intro n m hnm;
    -- We can prove this by induction on $m - n$.
    induction' hnm with m ih;
    · rfl;
    · exact List.IsPrefix.trans ‹_› ( iterateMorphism_prefix f a h_prolong m )

/-
If k <= m and the k-th iteration is long enough to have an n-th character, then the n-th character of the m-th iteration is the same as the n-th character of the k-th iteration.
-/
theorem iterateMorphism_stable_get {α : Type*} [Inhabited α] (f : Morphism α) (a : α) (h_prolong : Prolongable f a) :
  ∀ n k m, k ≤ m → n < (iterateMorphism f k a).length → (iterateMorphism f m a)[n]! = (iterateMorphism f k a)[n]! := by
    -- Let's choose any $n$, $k$, and $m$ such that $k \leq m$ and $n < (iterateMorphism f k a).length$.
    intro n k m hkm hn
    have h_prefix : iterateMorphism f k a <+: iterateMorphism f m a := by
      exact iterateMorphism_prefix_le f a h_prolong k m hkm;
    obtain ⟨ l, hl ⟩ := h_prefix;
    grind

/-
A morphism is non-erasing if it maps every letter to a non-empty word. If a morphism is prolongable on a and non-erasing, then the length of the n-th iteration of a grows at least as n + 1.
-/
def IsNonErasing {α : Type*} (f : Morphism α) : Prop :=
  ∀ a, f a ≠ []

theorem length_iterate_ge_succ_of_non_erasing {α : Type*} (f : Morphism α) (a : α) (h_prolong : Prolongable f a) (h_non_erasing : IsNonErasing f) :
  ∀ n, (iterateMorphism f n a).length ≥ n + 1 := by
    intro n
    induction' n with n ihrolong;
    · exact Nat.succ_le_of_lt ( List.length_pos_iff.mpr ( by tauto ) );
    · -- By definition of `iterateMorphism`, we have `iterateMorphism f (n + 1) a = applyMorphism f (iterateMorphism f n a)`.
      have h_iterate_succ : iterateMorphism f (n + 1) a = applyMorphism f (iterateMorphism f n a) := by
        rfl;
      unfold applyMorphism at h_iterate_succ;
      have h_length : (List.map f (iterateMorphism f n a)).flatten.length ≥ (iterateMorphism f n a).length + 1 := by
        have h_length : ∀ {l : List α}, (∀ x ∈ l, (f x).length ≥ 1) → (∃ x ∈ l, (f x).length ≥ 2) → (List.map f l).flatten.length ≥ l.length + 1 := by
          intros l hl_nonempty hl_ge_two
          induction' l with x l ih;
          · grind;
          · rcases hl_ge_two with ⟨ y, hy₁, hy₂ ⟩ ; rcases eq_or_ne y x with rfl | hy₃ <;> simp_all +decide [ List.map ];
            · linarith [ show ( List.map ( List.length ∘ f ) l ).sum ≥ l.length from by simpa using List.sum_le_sum fun x hx => hl_nonempty.2 x hx ];
            · linarith [ ih y hy₁ hy₂ ];
        apply h_length;
        · exact fun x hx => Nat.pos_of_ne_zero fun h => h_non_erasing x |> fun h' => h' <| List.length_eq_zero_iff.mp h;
        · obtain ⟨ u, hu ⟩ := h_prolong;
          use a;
          refine' ⟨ _, _ ⟩ <;> simp_all +decide [ iterateMorphism ];
          · refine' Nat.recOn n _ _ <;> simp_all +decide [ iterateMorphism ];
            intro n hn; unfold applyMorphism; simp_all +decide [ List.mem_flatten ] ;
            exact ⟨ a, hn, by simp +decide [ hu ] ⟩;
          · exact List.length_pos_iff.mpr hu.2;
      grind

/-
The n-th character of the limit word is equal to the n-th character of the k-th iteration of f on a, provided that the k-th iteration is long enough.
-/
theorem limitWord_eq_get {α : Type*} [Inhabited α] (f : Morphism α) (a : α) (h_prolong : Prolongable f a) (h_non_erasing : IsNonErasing f) :
  ∀ n k, n < (iterateMorphism f k a).length → limitWord f a h_prolong n = (iterateMorphism f k a)[n]! := by
    intro n k hn_lt_k
    by_cases hk : k ≤ n + 1;
    · convert iterateMorphism_stable_get f a h_prolong n k ( n + 1 ) ( by linarith ) ( by linarith ) using 1;
      unfold limitWord; aesop;
    · apply Eq.symm; exact (by
      rw [ limitWord ];
      split_ifs with h <;> simp_all +decide;
      · convert iterateMorphism_stable_get f a h_prolong n ( n + 1 ) k ( by linarith ) ( by linarith ) using 1;
        · exact Eq.symm (getElem!_pos (iterateMorphism f k a) n hn_lt_k);
        · exact Eq.symm (getElem!_pos (iterateMorphism f (n + 1) a) n h);
      · exact absurd h ( not_le_of_gt ( by linarith [ length_iterate_ge_succ_of_non_erasing f a h_prolong h_non_erasing ( n + 1 ) ] ) ))

/-
The prefix of length n of the limit word is equal to the prefix of length n of the (n+1)-th iteration of the morphism.
-/
theorem limitWord_prefix_eq_iterate_prefix {α : Type*} [Inhabited α] (f : Morphism α) (a : α) (h_prolong : Prolongable f a) (h_non_erasing : IsNonErasing f) :
  ∀ n, (List.range n).map (limitWord f a h_prolong) = (iterateMorphism f (n + 1) a).take n := by
    intros n
    apply List.ext_get;
    · have := length_iterate_ge_succ_of_non_erasing f a h_prolong h_non_erasing ( n + 1 ) ; simp_all +decide ; linarith;
    · simp +zetaDelta at *;
      intro i hi hp hq;
      convert limitWord_eq_get f a h_prolong h_non_erasing i ( n + 1 ) _;
      · exact?;
      · exact hq

/-
If h is an abelian square-free morphism prolongable on a, then h is non-erasing (maps every letter to a non-empty word).
-/
lemma asf_morphism_prolongable_implies_non_erasing {α : Type*} [DecidableEq α] (h : Morphism α) (a : α)
  (h_prolong : Prolongable h a) (h_asf : IsAbelianSquareFreeMorphism (applyMorphism h)) :
  IsNonErasing h := by
    -- Fix an arbitrary letter `b` in `α`.
    intro b
    by_cases h_eq : b = a;
    · cases h_prolong ; aesop;
    · -- Since `a` is abelian square-free and `b` is not equal to `a`, the word `[a, b, a]` is also abelian square-free.
      have h_ab_a_asf : IsAbelianSquareFree [a, b, a] := by
        intro s hs;
        rcases hs with ⟨ l, hl ⟩;
        rcases l with ( _ | ⟨ x, _ | ⟨ y, l ⟩ ⟩ ) <;> rcases s with ( _ | ⟨ x', _ | ⟨ y', s ⟩ ⟩ ) <;> simp_all +decide;
        · rintro ⟨ u, v, huv, hu, hv ⟩;
          rcases u with ( _ | ⟨ x, _ | ⟨ y, _ | ⟨ z, _ | u ⟩ ⟩ ⟩ ) <;> rcases v with ( _ | ⟨ x', _ | ⟨ y', _ | ⟨ z', _ | v ⟩ ⟩ ⟩ ) <;> simp_all +decide;
        · rintro ⟨ u, v, huv, hu, hv ⟩;
          rcases u with ( _ | ⟨ u, _ | ⟨ u, u ⟩ ⟩ ) <;> rcases v with ( _ | ⟨ v, _ | ⟨ v, v ⟩ ⟩ ) <;> simp_all +decide;
        · rintro ⟨ u, v, huv, hu, hv ⟩ ; aesop;
        · rintro ⟨ u, v, huv, hu, hv ⟩ ; cases u <;> cases v <;> aesop;
        · cases l <;> aesop;
      -- Applying the morphism `h` to `[a, b, a]` results in `h(a) ++ h(b) ++ h(a)`, which is abelian square-free.
      have h_h_ab_a_asf : IsAbelianSquareFree (applyMorphism h [a, b, a]) := by
        exact h_asf _ h_ab_a_asf;
      contrapose! h_h_ab_a_asf;
      unfold IsAbelianSquareFree; simp +decide [ *, applyMorphism ] ;
      exact ⟨ h a ++ h a, by simp +decide, ⟨ h a, h a, by simp +decide, by cases h_prolong; aesop ⟩ ⟩

/-
The prefix of length n of the limit word is equal to the prefix of length n of the (n+1)-th iteration of the morphism.
-/
lemma limit_word_prefix_eq_take_iterate {α : Type*} [Inhabited α] [DecidableEq α] (h : Morphism α) (a : α)
  (h_prolong : Prolongable h a) (h_asf : IsAbelianSquareFreeMorphism (applyMorphism h)) :
  ∀ n, (List.range n).map (limitWord h a h_prolong) = (iterateMorphism h (n + 1) a).take n := by
    -- Apply `limitWord_prefix_eq_iterate_prefix` with the non-erasing fact to conclude the proof.
    have h_nonerasing : IsNonErasing h := by
      exact asf_morphism_prolongable_implies_non_erasing h a h_prolong h_asf
    apply limitWord_prefix_eq_iterate_prefix h a h_prolong h_nonerasing

/-
Defining "IsFactorFree" as having no abelian square subword (factor), and "IsFactorFreeMorphism" as preserving this property. This corresponds to the text's definition of "abelian square-free".
-/
def IsFactorFree {α : Type*} (w : List α) : Prop :=
  ∀ s, s <:+: w → ¬ IsAbelianSquare s

def IsFactorFreeMorphism {α : Type*} (h : Morphism α) : Prop :=
  ∀ w, IsFactorFree w → IsFactorFree (applyMorphism h w)

/-
Let $h: \Sigma^* \to \Sigma^*$ be a morphism. If there exists $N \in \mathbb{N}$ such that for every abelian square-free word $w$ with $|w| \leq N$, the image $h(w)$ is abelian square-free, then $h$ is abelian square-free.
-/
lemma factor_check_factor {α : Type*} [Fintype α] (h : Morphism α) :
  ∃ N, (∀ w, IsFactorFree w → w.length ≤ N → IsFactorFree (applyMorphism h w)) →
  IsFactorFreeMorphism h := by
    -- If `IsFactorFreeMorphism h` is true, then the statement is true.
    by_cases h_factor_free : IsFactorFreeMorphism h;
    · exact ⟨ 0, fun _ => h_factor_free ⟩;
    · -- By definition of `IsFactorFreeMorphism`, there exists some word `w` such that `IsFactorFree w` but `¬IsFactorFree (h w)`.
      obtain ⟨w, hw⟩ : ∃ w : List α, IsFactorFree w ∧ ¬IsFactorFree (applyMorphism h w) := by
        exact Set.not_subset.mp h_factor_free;
      exact ⟨ w.length, fun h' => False.elim ( hw.2 ( h' w hw.1 le_rfl ) ) ⟩

/-
An infinite word is abelian square-free (factor-free) if every finite prefix is abelian square-free.
-/
def IsFactorFreeInfinite {α : Type*} (w : ℕ → α) : Prop :=
  ∀ n, IsFactorFree ((List.range n).map w)

/-
The morphism $g$ is prolongable on $a$.
-/
lemma g_prolongable : Prolongable g a := by
  unfold Prolongable; aesop;

/-
A computable decision procedure for abelian squares.
-/
def decideAbelianSquare (w : List Alphabet) : Bool :=
  w.length % 2 == 0 && w.length > 0 && decide ((w.take (w.length / 2)).Perm (w.drop (w.length / 2)))

theorem decideAbelianSquare_iff (w : List Alphabet) : decideAbelianSquare w ↔ IsAbelianSquare w := by
  unfold decideAbelianSquare;
  constructor <;> intro h;
  · have h_perm : List.Perm (List.take (w.length / 2) w) (List.drop (w.length / 2) w) := by
      grind;
    use List.take ( w.length / 2 ) w, List.drop ( w.length / 2 ) w;
    norm_num +zetaDelta at *;
    exact ⟨ ⟨ by omega, by aesop_cat ⟩, h.2 ⟩;
  · obtain ⟨ u, v, rfl, hu, hv ⟩ := h; simp_all +decide ;
    have := hv.length_eq; simp_all +arith +decide;
    exact this ▸ List.length_pos_iff.mpr hu

/-
A computable decision procedure for abelian square-free words.
-/
def decideFactorFree (w : List Alphabet) : Bool :=
  (w.tails.flatMap List.inits).all fun s => !decideAbelianSquare s

theorem decideFactorFree_iff (w : List Alphabet) : decideFactorFree w ↔ IsFactorFree w := by
  -- By definition of `decideFactorFree`, it returns true if and only if all subwords of `w` are not abelian squares.
  simp [decideFactorFree, IsFactorFree];
  constructor <;> intro h s hs;
  · obtain ⟨ t, ht, ht' ⟩ := hs;
    contrapose! h;
    exact ⟨ s ++ ht, by aesop, s, by aesop, by simpa [ decideAbelianSquare_iff ] using h ⟩;
  · contrapose! h;
    -- Since $x$ is a prefix of $s$ and $s$ is a suffix of $w$, $x$ is also a subword of $w$.
    obtain ⟨x, hx_prefix, hx_ab_sq⟩ := h;
    have hx_subword : x <:+: w := by
      grind;
    exact ⟨ x, hx_subword, by simpa using decideAbelianSquare_iff x |>.1 ( by simpa using hx_ab_sq ) ⟩

/-
If h is a factor-free morphism and a is a factor-free letter, then all iterations h^n(a) are factor-free.
-/
lemma iterate_factor_free {α : Type*} (h : Morphism α) (a : α) (n : ℕ)
  (h_asf : IsFactorFreeMorphism h) (ha : IsFactorFree [a]) :
  IsFactorFree (iterateMorphism h n a) := by
    -- We proceed by induction on $n$.
    induction' n with k ih;
    · exact ha;
    · convert h_asf _ ih

/-
Alphabet is a finite type.
-/
instance : Fintype Alphabet where
  elems := {a, b, c, d}
  complete := by
    intro x
    cases x <;> simp

/-
The bound N provided by the factor check lemma.
-/
noncomputable def keranen_N : ℕ := (factor_check_factor g).choose

/-
Conditional proof of Keranen's theorem.
-/
theorem keranen_conditional (h : ∀ w, IsFactorFree w → w.length ≤ keranen_N → IsFactorFree (applyMorphism g w)) : IsFactorFreeMorphism g := by
  exact (factor_check_factor g).choose_spec h

/-
Assumption that the computational check holds.
-/
variable (keranen_check_assumption : ∀ w, IsFactorFree w → w.length ≤ keranen_N → IsFactorFree (applyMorphism g w))

/-
The limit word of the morphism g starting from a.
-/
noncomputable def g_limit : ℕ → Alphabet :=
  limitWord g a g_prolongable

/-
There exists an infinite abelian square-free word over a four-letter alphabet (constructed as the limit of g).
-/
theorem corollary_keranen (h_check : ∀ w, IsFactorFree w → w.length ≤ keranen_N → IsFactorFree (applyMorphism g w)) :
  IsFactorFreeInfinite g_limit := by
    -- By definition of `g_limit`, we know that every finite prefix of it is a prefix of some iteration of `g` on `a`.
    have h_prefix : ∀ n, (List.range n).map (limitWord g a g_prolongable) = (iterateMorphism g (n + 1) a).take n := by
      convert limit_word_prefix_eq_take_iterate using 1;
      rotate_left;
      exact Alphabet;
      exact instInhabitedAlphabet;
      · infer_instance;
      · constructor;
        · exact fun a h a h_prolong h_asf n =>
          limit_word_prefix_eq_take_iterate h a h_prolong h_asf n;
        · intro h n;
          convert limitWord_prefix_eq_iterate_prefix using 1;
          rotate_left;
          exact Alphabet;
          exact instInhabitedAlphabet;
          constructor <;> intro h;
          · exact fun f a h_prolong h_non_erasing n =>
            limitWord_prefix_eq_iterate_prefix f a h_prolong h_non_erasing n;
          · convert h g a g_prolongable _ n;
            intro a; exact (by
            decide +revert);
    -- Since `g` is prolongable on `a` and `a` is factor-free (being a single letter), and `g` is factor-free (by the check and Lemma 2), by Lemma 1 (morphism preserves), the infinite word `g^omega(a)` is factor-free.
    have h_factor_free : ∀ n, IsFactorFree (iterateMorphism g n a) := by
      -- By definition of `g_limit`, we know that every finite prefix of it is a prefix of some iteration of `g` on `a`. Since `g` is abelian square-free, these prefixes are also abelian square-free. We prove this by induction on `n` using the fact that `g` is abelian square-free.
      intros n
      apply iterate_factor_free g a n (keranen_conditional h_check) (by
      exact (decideFactorFree_iff [a]).mp rfl);
    intro n
    specialize h_prefix n
    specialize h_factor_free (n + 1);
    -- By definition of `IsFactorFree`, if `s` is a subword of `List.take n (iterateMorphism g (n + 1) a)`, then `s` is also a subword of `iterateMorphism g (n + 1) a`.
    have h_subword : ∀ s, s <:+: List.take n (iterateMorphism g (n + 1) a) → s <:+: iterateMorphism g (n + 1) a := by
      intro s hs
      obtain ⟨i, hi⟩ := hs;
      obtain ⟨ t, ht ⟩ := hi;
      use i, t ++ List.drop n (iterateMorphism g (n + 1) a);
      rw [ ← List.append_assoc, ← List.take_append_drop n ( iterateMorphism g ( n + 1 ) a ), ← ht ];
      simp +decide [ ht ];
    exact fun s hs => h_factor_free s ( h_subword s ( h_prefix ▸ hs ) )

#print axioms corollary_keranen