/-
Below you can find a former formalization of the first two theorems in my paper 'The binomial case of Graham's conjecture on polynomial representations with prescribed sum of reciprocals'. This paper has since been updated, making the formalization (generated by Aristotle from Harmonic (https://aristotle.harmonic.fun)) obsolete.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definitions of f(x), sum_f, sum_inv, sum_pow, is_positive_set, n_0 and scale_set m A = {ma | a ∈ A}.
-/
open Finset

def f_poly (a b c x : ℕ) : ℕ := a * x^c + b
def sum_f (a b c : ℕ) (A : Finset ℕ) : ℕ := ∑ x ∈ A, f_poly a b c x
def sum_inv (A : Finset ℕ) : ℚ := ∑ x ∈ A, (1 / (x : ℚ))
def sum_pow (c : ℕ) (A : Finset ℕ) : ℕ := ∑ x ∈ A, x^c
def is_positive_set (A : Finset ℕ) : Prop := ∀ x ∈ A, 0 < x
def n_0_set (a b c : ℕ) (alpha : ℚ) : Set ℕ :=
  { k | ∀ n ≥ k, ∃ A : Finset ℕ, is_positive_set A ∧ sum_f a b c A = n ∧ sum_inv A = alpha }
noncomputable def n_0 (a b c : ℕ) (alpha : ℚ) : ℕ := sInf (n_0_set a b c alpha)
def scale_set (m : ℕ) (A : Finset ℕ) : Finset ℕ := A.image (fun x => m * x)

/-
Definition of the SixProperties structure required for the meta theorem.
-/
open Finset

structure SixProperties (c : ℕ) (S : Set ℚ) (Q : Finset ℕ → Prop) (m s : ℕ) (beta : S → Fin (m^c) → ℚ) (A_fam : S → Fin (m^c) → Finset ℕ) : Prop where
  prop1 : ∀ (alpha : S) (i : Fin (m^c)), beta alpha i ∈ S
  prop2 : ∀ (alpha : S) (i : Fin (m^c)), Nat.ModEq (m^c) (sum_pow c (A_fam alpha i)) i.val
  prop3 : ∀ (alpha : S) (i : Fin (m^c)), (A_fam alpha i).card = s
  prop4 : ∀ (alpha : S) (i : Fin (m^c)), (alpha : ℚ) = sum_inv (A_fam alpha i) + (beta alpha i) / (m : ℚ)
  prop5 : ∀ (alpha : S) (i : Fin (m^c)) (B : Finset ℕ), Q B → Disjoint (A_fam alpha i) (scale_set m B)
  prop6 : ∀ (alpha : S) (i : Fin (m^c)) (B : Finset ℕ), Q B → Q ((A_fam alpha i) ∪ (scale_set m B))

/-
Definition of MetaAssumptions and MetaTheoremStatement.
-/
open Finset

structure MetaAssumptions (a b c : ℕ) (S : Set ℚ) (Q : Finset ℕ → Prop) (m s : ℕ)
  (beta : S → Fin (m^c) → ℚ) (A_fam : S → Fin (m^c) → Finset ℕ)
  (M L X r : ℕ) : Prop where
  h_pos_coeff : 0 < a ∧ 0 < b
  h_coprime_ab : a.Coprime b
  h_c_pos : 0 < c
  h_S_pos : ∀ q ∈ S, 0 < q
  h_s_div : a ∣ s
  h_m_ge_2 : 2 ≤ m
  h_coprime_ma : m.Coprime a
  h_A_pos : ∀ (alpha : S) (i : Fin (m^c)), is_positive_set (A_fam alpha i)
  h_six : SixProperties c S Q m s beta A_fam
  h_M : ∀ (alpha : S) (i : Fin (m^c)), sum_pow c (A_fam alpha i) ≤ M
  h_L : ∀ (alpha : S) (i : Fin (m^c)), L ≤ sum_pow c (A_fam alpha i)
  h_X_pos : 0 < X
  h_r_pos : 0 < r
  h_ineq : ((m^c : ℤ) - 1) * b * ((r : ℤ) * ((m^c : ℤ) - 1) - s) ≥ a * ((M : ℤ) - L)
  h_base_cases : ∀ (alpha : S) (n : ℕ), X ≤ n → n ≤ m^c * X + a * M → n ≡ b * r [MOD a] →
    ∃ A, Q A ∧ A.card = r ∧ sum_f a b c A = n ∧ sum_inv A = alpha

def MetaTheoremStatement (a b c : ℕ) (S : Set ℚ) (Q : Finset ℕ → Prop) (m s : ℕ)
  (beta : S → Fin (m^c) → ℚ) (A_fam : S → Fin (m^c) → Finset ℕ)
  (M L X r : ℕ) : Prop :=
  MetaAssumptions a b c S Q m s beta A_fam M L X r →
  ∀ (alpha : S) (n : ℕ), X ≤ n → n ≡ b * r [MOD a] →
    ∃ A, Q A ∧ sum_f a b c A = n ∧ sum_inv A = alpha

/-
Marking MetaTheoremStatement as irreducible to prevent the ATP from unfolding it during the proof attempt of the meta theorem.
-/
attribute [irreducible] MetaTheoremStatement

/-
Definition of Y as given in the proof: Y := m^cX - b(r(m^c-1)-s) + aM.
-/
def Y_val (a b c m s M X r : ℕ) : ℤ := (m^c : ℤ) * X - b * ((r : ℤ) * ((m^c : ℤ) - 1) - s) + a * M

/-
Lemma: M >= m^c - 1, assuming S is nonempty.
-/
lemma M_ge_mc_sub_one {a b c : ℕ} {S : Set ℚ} {Q : Finset ℕ → Prop} {m s : ℕ} {beta : S → Fin (m^c) → ℚ} {A_fam : S → Fin (m^c) → Finset ℕ} {M L X r : ℕ} (h : MetaAssumptions a b c S Q m s beta A_fam M L X r) (hS : S.Nonempty) :
  M ≥ m^c - 1 := by
  cases' h with h_pos_coeff h_coprime_ab h_c_pos h_S_pos h_s_div h_m_ge_2 h_coprime_ma h_A_pos h_six h_M h_L h_X_pos h_r_pos h_ineq h_base_cases;
  obtain ⟨alpha, halpha⟩ : ∃ alpha : S, True := by
    exact ⟨ ⟨ hS.some, hS.choose_spec ⟩, trivial ⟩
  obtain ⟨i, hi⟩ : ∃ i : Fin (m^c), (m^c - 1 : ℕ) ≤ _root_.sum_pow c (A_fam alpha i) := by
    have := h_six.prop2 alpha ⟨ m ^ c - 1, Nat.sub_lt ( by positivity ) ( by positivity ) ⟩ ; simp_all +decide [ Nat.ModEq ] ;
    exact ⟨ _, by linarith [ Nat.mod_le ( _root_.sum_pow c ( A_fam alpha ⟨ m ^ c - 1, Nat.sub_lt ( by positivity ) ( by positivity ) ⟩ ) ) ( m ^ c ), Nat.sub_add_cancel ( Nat.one_le_pow c m ( by positivity ) ) ] ⟩ ;
  generalize_proofs at *; (
  exact le_trans hi ( h_M alpha i ))

/-
Lemma: X > br - a.
-/
lemma X_gt_br_sub_a {a b c : ℕ} {S : Set ℚ} {Q : Finset ℕ → Prop} {m s : ℕ} {beta : S → Fin (m^c) → ℚ} {A_fam : S → Fin (m^c) → Finset ℕ} {M L X r : ℕ} (h : MetaAssumptions a b c S Q m s beta A_fam M L X r) (hS : S.Nonempty) :
  (X : ℤ) > (b * r : ℤ) - a := by
  cases' h with h_pos_coeff h_coprime_ab h_c_pos h_S_pos h_s_div h_m_ge_2 h_coprime_ma h_A_pos h_six h_M h_L h_X_pos h_r_pos h_ineq h_base_cases
  generalize_proofs at *; simp_all +decide ; (
  -- Assume for contradiction that $X \leq br - a$.
  by_contra h_contra
  generalize_proofs at *; (
  -- Since $X \leq br - a$, we have $br - a \in [X, m^c X + a M]$.
  have h_br_minus_a_in_interval : b * r - a ≤ m ^ c * X + a * M := by
    have h_br_minus_a_in_interval : ∃ n ∈ Finset.Icc X (m ^ c * X + a * M), n ≡ b * r [MOD a] := by
      -- Since $m^c \geq 2$, the interval $[X, m^c X + a M]$ contains at least $a$ consecutive integers.
      have h_interval_length : m ^ c * X + a * M - X ≥ a := by
        have h_interval_length : m ^ c ≥ 2 := by
          exact le_trans h_m_ge_2 ( Nat.le_self_pow h_c_pos.ne' _ )
        generalize_proofs at *; (
        by_cases hM : M = 0
        generalize_proofs at *; (
        have := h_six.prop2; simp_all +decide ;
        specialize this _ hS.choose_spec ⟨ 1, by linarith ⟩ ; norm_num [ Nat.modEq_iff_dvd ] at this; norm_cast at this; aesop;);
        exact le_tsub_of_add_le_left ( by nlinarith [ Nat.pos_of_ne_zero hM ] ) ;)
      generalize_proofs at *; (
      -- Since the interval $[X, m^c X + a M]$ contains at least $a$ consecutive integers, there must be some $n$ in this interval such that $n \equiv b * r \pmod{a}$.
      have h_exists_n : ∃ n ∈ Finset.range a, (X + n) ≡ b * r [MOD a] := by
        use ( b * r + a - X % a ) % a; simp +decide [ Nat.ModEq, Nat.mod_lt, * ] ;
        simp +decide [ ← ZMod.natCast_eq_natCast_iff', Nat.cast_sub ( show X % a ≤ b * r + a from by linarith [ Nat.zero_le ( X % a ), Nat.mod_lt X h_pos_coeff.1 ] ) ]
      generalize_proofs at *; (
      exact ⟨ X + h_exists_n.choose, Finset.mem_Icc.mpr ⟨ by linarith [ Finset.mem_range.mp h_exists_n.choose_spec.1 ], by linarith [ Finset.mem_range.mp h_exists_n.choose_spec.1, Nat.sub_add_cancel ( show X ≤ m ^ c * X + a * M from by nlinarith [ pow_pos ( zero_lt_two.trans_le h_m_ge_2 ) c ] ) ] ⟩, h_exists_n.choose_spec.2 ⟩ ;))
    generalize_proofs at *; (
    obtain ⟨ n, hn₁, hn₂ ⟩ := h_br_minus_a_in_interval
    generalize_proofs at *; (
    obtain ⟨ A, hA₁, hA₂, hA₃, hA₄ ⟩ := h_base_cases _ hS.choose_spec _ ( Finset.mem_Icc.mp hn₁ |>.1 ) ( Finset.mem_Icc.mp hn₁ |>.2 ) hn₂ ; simp_all +decide [ sum_f ] ; (
    -- Since $A$ is a finite set of positive integers, we have $\sum_{x \in A} f_poly a b c x \geq a \sum_{x \in A} x^c + b |A|$.
    have h_sum_ge : ∑ x ∈ A, f_poly a b c x ≥ a * ∑ x ∈ A, x^c + b * A.card := by
      simp +decide [ Finset.mul_sum _ _ _, Finset.sum_add_distrib, mul_comm, f_poly ]
    generalize_proofs at *; (
    grind))))
  generalize_proofs at *; (
  -- Applying the hypothesis `h_base_cases` to $n = br - a$, we get a contradiction.
  obtain ⟨A, hA_Q, hA_card, hA_sum_f, hA_sum_inv⟩ := h_base_cases (Classical.choose hS) (Classical.choose_spec hS) (b * r - a) (by
  exact Nat.le_sub_of_add_le ( by linarith [ Nat.sub_add_cancel ( show a ≤ b * r from le_of_not_gt fun h => by rw [ tsub_eq_zero_iff_le.mpr h.le ] at *; linarith ) ] )) (by
  exact h_br_minus_a_in_interval) (by
  simp +decide [ ← ZMod.natCast_eq_natCast_iff, Nat.cast_sub ( show a ≤ b * r from by nlinarith [ Nat.sub_add_cancel ( show a ≤ b * r from by nlinarith ) ] ) ]);
  -- Since $A$ is a finite set of positive integers, we have $\sum_{x \in A} f(x) \geq a \sum_{x \in A} x^c + b |A|$.
  have h_sum_f_ge : sum_f a b c A ≥ a * (∑ x ∈ A, x ^ c) + b * A.card := by
    unfold sum_f; simp +decide [ Finset.mul_sum _ _ _ ] ;
    unfold f_poly; simp +decide [ mul_comm, Finset.sum_add_distrib ] ;
  generalize_proofs at *; (
  grind))))

/-
Lemma: r(m^c-1) - s >= 0.
-/
lemma term_nonneg {a b c : ℕ} {S : Set ℚ} {Q : Finset ℕ → Prop} {m s : ℕ} {beta : S → Fin (m^c) → ℚ} {A_fam : S → Fin (m^c) → Finset ℕ} {M L X r : ℕ} (h : MetaAssumptions a b c S Q m s beta A_fam M L X r) (hS : S.Nonempty) :
  (r : ℤ) * ((m^c : ℤ) - 1) - s ≥ 0 := by
  have h_nonneg : (a * (M - L) : ℤ) ≥ 0 := by
    cases' hS with x hx;
    exact mul_nonneg ( Nat.cast_nonneg _ ) ( sub_nonneg.mpr <| mod_cast h.h_M ⟨ x, hx ⟩ ⟨ 0, pow_pos ( zero_lt_two.trans_le h.h_m_ge_2 ) _ ⟩ |> le_trans ( h.h_L ⟨ x, hx ⟩ ⟨ 0, pow_pos ( zero_lt_two.trans_le h.h_m_ge_2 ) _ ⟩ ) );
  have h_pos : (m^c - 1 : ℤ) * b > 0 := by
    exact mul_pos ( sub_pos.mpr ( one_lt_pow₀ ( mod_cast h.h_m_ge_2 ) ( by linarith [ h.h_c_pos ] ) ) ) ( mod_cast h.h_pos_coeff.2 );
  nlinarith [ h.h_ineq ]

/-
Lemma: X < Y <= m^c X + a M.
-/
lemma Y_bounds {a b c : ℕ} {S : Set ℚ} {Q : Finset ℕ → Prop} {m s : ℕ} {beta : S → Fin (m^c) → ℚ} {A_fam : S → Fin (m^c) → Finset ℕ} {M L X r : ℕ} (h : MetaAssumptions a b c S Q m s beta A_fam M L X r) (hS : S.Nonempty) :
  (X : ℤ) < Y_val a b c m s M X r ∧ Y_val a b c m s M X r ≤ (m^c : ℤ) * X + a * M := by
  refine' ⟨ _, _ ⟩;
  · -- We know that $X > br - a$ from `X_gt_br_sub_a`.
    have hX_gt_br_sub_a : (X : ℤ) > (b * r : ℤ) - a := by
      exact X_gt_br_sub_a h hS;
    -- We know that $M \geq m^c - 1$ from `M_ge_mc_sub_one`.
    have hM_ge_mc_sub_one : (M : ℤ) ≥ (m^c : ℤ) - 1 := by
      convert M_ge_mc_sub_one h hS using 1;
      grind;
    unfold Y_val; nlinarith [ show ( m ^ c : ℤ ) > 1 from mod_cast one_lt_pow₀ ( show 1 < m from by linarith [ h.h_m_ge_2 ] ) ( show c ≠ 0 from by linarith [ h.h_c_pos ] ) ] ;
  · unfold Y_val; nlinarith [ term_nonneg h hS ] ;

/-
Reduction Lemma: If n is in [Y, m^c Y + a M] and n = b(r+s) [mod a], then a solution exists.
-/
lemma reduction_lemma {a b c : ℕ} {S : Set ℚ} {Q : Finset ℕ → Prop} {m s : ℕ} {beta : S → Fin (m^c) → ℚ} {A_fam : S → Fin (m^c) → Finset ℕ} {M L X r : ℕ} (h : MetaAssumptions a b c S Q m s beta A_fam M L X r) (hS : S.Nonempty) :
  let Y := Y_val a b c m s M X r
  ∀ (alpha : S) (n : ℕ), Y ≤ n → n ≤ (m^c : ℤ) * Y + a * M → n ≡ b * (r + s) [MOD a] →
    ∃ A, Q A ∧ A.card = r + s ∧ sum_f a b c A = n ∧ sum_inv A = alpha := by
  obtain ⟨alpha⟩ := hS
  obtain ⟨h_pos_coeff, h_coprime_ab, h_c_pos, h_S_pos, h_s_div, h_m_ge_2, h_coprime_ma, h_A_pos, h_six, h_M, h_L, h_X_pos, h_r_pos, h_ineq, h_base_cases⟩ := h;
  intro Y alpha n hn₁ hn₂ hn₃
  obtain ⟨i, hi⟩ : ∃ i : Fin (m ^ c), a * _root_.sum_pow c (A_fam alpha i) ≡ n + b * ((r : ℤ) * ((m ^ c : ℤ) - 1) - s) [ZMOD (m ^ c : ℤ)] := by
    have h_inv : ∃ i : Fin (m ^ c), _root_.sum_pow c (A_fam alpha i) ≡ (n + b * ((r : ℤ) * ((m ^ c : ℤ) - 1) - s)) * (a ^ (Nat.totient (m ^ c) - 1)) [ZMOD (m ^ c : ℤ)] := by
      have h_inv : ∀ i : Fin (m ^ c), _root_.sum_pow c (A_fam alpha i) ≡ i.val [ZMOD (m ^ c : ℤ)] := by
        intro i; specialize h_six; have := h_six.prop2 alpha i; simp_all +decide [ ← Int.natCast_modEq_iff ] ;
      use ⟨ Int.toNat ( ( n + b * ( r * ( m ^ c - 1 ) - s ) ) * a ^ ( φ ( m ^ c ) - 1 ) % ( m ^ c ) ), by
        linarith [ Int.emod_lt_of_pos ( ( n + b * ( r * ( m ^ c - 1 ) - s ) ) * a ^ ( φ ( m ^ c ) - 1 ) ) ( by positivity : 0 < ( m ^ c : ℤ ) ), Int.toNat_of_nonneg ( Int.emod_nonneg ( ( n + b * ( r * ( m ^ c - 1 ) - s ) ) * a ^ ( φ ( m ^ c ) - 1 ) ) ( by positivity : ( m ^ c : ℤ ) ≠ 0 ) ) ] ⟩
      generalize_proofs at *;
      exact Eq.trans ( h_inv _ ) ( by simp +decide [Int.emod_nonneg _
            (by positivity : (m ^ c : ℤ) ≠ 0)] );
    obtain ⟨ i, hi ⟩ := h_inv
    have h_cong : a ^ Nat.totient (m ^ c) ≡ 1 [ZMOD (m ^ c : ℤ)] := by
      simpa [ ← Int.natCast_modEq_iff ] using Nat.ModEq.pow_totient <| Nat.Coprime.gcd_eq_one <| Nat.Coprime.pow_right _ <| h_coprime_ma.symm.trans <| by aesop;
    have h_cong' : a * a ^ (Nat.totient (m ^ c) - 1) ≡ 1 [ZMOD (m ^ c : ℤ)] := by
      rwa [ ← pow_succ', Nat.sub_add_cancel ( Nat.one_le_iff_ne_zero.mpr <| by aesop ) ] at *;
    have h_cong'' : a * (n + b * ((r : ℤ) * ((m ^ c : ℤ) - 1) - s)) * a ^ (Nat.totient (m ^ c) - 1) ≡ (n + b * ((r : ℤ) * ((m ^ c : ℤ) - 1) - s)) [ZMOD (m ^ c : ℤ)] := by
      convert h_cong'.mul_left ( n + b * ( r * ( m ^ c - 1 ) - s ) ) using 1 <;> ring
    have h_cong''' : a * _root_.sum_pow c (A_fam alpha i) ≡ (n + b * ((r : ℤ) * ((m ^ c : ℤ) - 1) - s)) [ZMOD (m ^ c : ℤ)] := by
      exact Eq.trans ( Int.ModEq.mul_left _ hi ) ( by simpa [ mul_assoc ] using h_cong'' )
    exact ⟨ i, h_cong''' ⟩;
  -- Let $n' = \frac{n - a \sum_{x \in A_i} x^c + b(r(m^c-1)-s)}{m^c}$.
  obtain ⟨n', hn'⟩ : ∃ n' : ℕ, n = a * _root_.sum_pow c (A_fam alpha i) + m^c * n' - b * ((r : ℤ) * ((m ^ c : ℤ) - 1) - s) ∧ X ≤ n' ∧ n' ≤ m^c * X + a * M ∧ n' ≡ b * r [MOD a] := by
    obtain ⟨n', hn'⟩ : ∃ n' : ℤ, n = a * _root_.sum_pow c (A_fam alpha i) + m^c * n' - b * ((r : ℤ) * ((m ^ c : ℤ) - 1) - s) ∧ X ≤ n' ∧ n' ≤ m^c * X + a * M := by
      obtain ⟨n', hn'⟩ : ∃ n' : ℤ, n = a * _root_.sum_pow c (A_fam alpha i) + m^c * n' - b * ((r : ℤ) * ((m ^ c : ℤ) - 1) - s) := by
        obtain ⟨ k, hk ⟩ := hi.symm.dvd; exact ⟨ -k, by linarith ⟩ ;
      refine' ⟨ n', hn', _, _ ⟩ <;> norm_num [ Y_val ] at *;
      · simp +zetaDelta at *;
        unfold Y_val at *; nlinarith [ pow_le_pow_right₀ ( by linarith : 1 ≤ m ) h_c_pos, h_M _ alpha.2 i, h_L _ alpha.2 i ] ;
      · norm_num +zetaDelta at *;
        unfold Y_val at *;
        nlinarith [ pow_pos ( zero_lt_two.trans_le h_m_ge_2 ) c, h_M _ alpha.2 i, h_L _ alpha.2 i ];
    refine' ⟨ Int.toNat n', _, _, _, _ ⟩ <;> norm_num [ Int.toNat_of_nonneg ( by linarith : 0 ≤ n' ) ] at *;
    · exact hn'.1;
    · grind;
    · linarith;
    · rw [ ← Int.natCast_modEq_iff ] at *;
      simp_all +decide [ Int.ModEq ];
      rw [ max_eq_left ( by linarith ) ] ; simp_all +decide [ ← ZMod.intCast_eq_intCast_iff' ] ;
      have h_cancel : IsUnit (m ^ c : ZMod a) := by
        have h_cancel : IsUnit (m : ZMod a) := by
          exact (ZMod.isUnit_iff_coprime m a).mpr h_coprime_ma;
        exact h_cancel.pow _;
      exact h_cancel.mul_left_inj.mp ( by linear_combination' hn₃ );
  obtain ⟨B, hB⟩ := h_base_cases ⟨beta alpha i, h_six.prop1 alpha i⟩ n' hn'.right.left hn'.right.right.left hn'.right.right.right;
  refine' ⟨ A_fam alpha i ∪ scale_set m B, _, _, _, _ ⟩;
  · exact h_six.prop6 _ _ _ hB.1;
  · rw [ Finset.card_union_of_disjoint ];
    · rw [ show scale_set m B = B.image ( fun x => m * x ) by rfl, Finset.card_image_of_injective _ fun x y hxy => mul_left_cancel₀ ( by linarith ) hxy ] ; linarith [ h_six.prop3 alpha i ];
    · exact h_six.prop5 alpha i B hB.1;
  · unfold sum_f scale_set at *;
    rw [ Finset.sum_union ];
    · rw [ Finset.sum_image ] <;> norm_num [ f_poly ];
      · norm_num [ Finset.sum_add_distrib, mul_pow, ← Finset.mul_sum _ _ _, ← Finset.sum_mul, _root_.sum_pow ] at *;
        unfold f_poly at hB; norm_num [ Finset.sum_add_distrib, mul_add, add_assoc, mul_assoc, mul_comm, mul_left_comm, Finset.mul_sum _ _ _, Finset.sum_mul ] at *;
        norm_num [ ← mul_assoc, ← Finset.sum_mul _ _ _, hB.2.1 ] at *;
        norm_num [ ← Finset.mul_sum _ _ _, ← Finset.sum_mul ] at *;
        rw [ show # ( A_fam alpha i ) = s from h_six.prop3 alpha i ] ; nlinarith [ pow_pos ( zero_lt_two.trans_le h_m_ge_2 ) c ] ;
      · exact fun x hx y hy hxy => mul_left_cancel₀ ( by linarith : m ≠ 0 ) hxy;
    · exact h_six.prop5 alpha i B hB.1;
  · -- By definition of $sum_inv$, we have:
    have h_sum_inv_union : sum_inv (A_fam alpha i ∪ scale_set m B) = sum_inv (A_fam alpha i) + sum_inv (scale_set m B) := by
      apply Finset.sum_union; exact (by
      exact h_six.prop5 alpha i B hB.1);
    generalize_proofs at *; simp_all +decide ; (
    -- By definition of $scale_set$, we have:
    have h_sum_inv_scale : sum_inv (scale_set m B) = (1 / m : ℚ) * sum_inv B := by
      unfold sum_inv scale_set; simp +decide [Finset.mul_sum _ _ _] ;
      rw [ Finset.sum_image ] <;> norm_num [ mul_comm, ne_of_gt ( zero_lt_two.trans_le h_m_ge_2 ) ]
    generalize_proofs at *; simp_all +decide ; (
    have := h_six.prop4 alpha i; simp_all +decide ; (
    ring)))

/-
Definitions of the sequences r_k and X_k used in the proof of the meta theorem.
-/
def r_seq_def (r s k : ℕ) : ℕ := r + k * s

def X_seq_def (a b c m s M r X : ℕ) (k : ℕ) : ℕ :=
  Nat.rec X (fun k x_k => Int.toNat (Y_val a b c m s M x_k (r_seq_def r s k))) k

/-
Step reduction lemma: if solutions exist for (X_prev, r_prev), they exist for (Y, r_prev + s).
-/
lemma step_reduction_lemma {a b c : ℕ} {S : Set ℚ} {Q : Finset ℕ → Prop} {m s : ℕ} {beta : S → Fin (m^c) → ℚ} {A_fam : S → Fin (m^c) → Finset ℕ} {M L X r : ℕ} (h : MetaAssumptions a b c S Q m s beta A_fam M L X r) (hS : S.Nonempty)
  (X_prev r_prev : ℕ) (h_r_ge : r_prev ≥ r)
  (h_prev : ∀ (alpha : S) (n : ℕ), X_prev ≤ n → n ≤ m^c * X_prev + a * M → n ≡ b * r_prev [MOD a] → ∃ A, Q A ∧ A.card = r_prev ∧ sum_f a b c A = n ∧ sum_inv A = alpha) :
  let Y := Y_val a b c m s M X_prev r_prev
  ∀ (alpha : S) (n : ℕ), Y ≤ n → n ≤ (m^c : ℤ) * Y + a * M → n ≡ b * (r_prev + s) [MOD a] →
    ∃ A, Q A ∧ A.card = r_prev + s ∧ sum_f a b c A = n ∧ sum_inv A = alpha := by
      convert @reduction_lemma a b c S Q m s beta A_fam M L X_prev ( r_prev ) using 1;
      refine' ⟨ fun h => fun _ _ => h, fun h => h _ hS ⟩;
      rename_i h';
      cases h';
      constructor <;> try assumption;
      · contrapose! h_prev;
        use ⟨ Classical.choose hS, Classical.choose_spec hS ⟩, b * r_prev % a;
        simp +zetaDelta at *;
        refine' ⟨ _, _, _, _ ⟩;
        · exact h_prev.symm ▸ Nat.zero_le _;
        · exact le_trans ( Nat.le_of_lt ( Nat.mod_lt _ ( by linarith ) ) ) ( by nlinarith [ show 0 < m ^ c by positivity, show 0 < a by linarith, show 0 < M by
                                                                                                                                                    have := M_ge_mc_sub_one ( show MetaAssumptions a b c S Q m s beta A_fam M L X r from by
                                                                                                                                                                                constructor <;> try assumption;
                                                                                                                                                                                · aesop;
                                                                                                                                                                                · aesop;
                                                                                                                                                                                · aesop;
                                                                                                                                                                                · aesop ) hS
                                                                                                                                                    generalize_proofs at *;
                                                                                                                                                    exact lt_of_lt_of_le ( Nat.sub_pos_of_lt ( one_lt_pow₀ ( by linarith ) ( by linarith ) ) ) this ] );
        · norm_num [ Nat.ModEq ];
        · intro x hx hx' hx''; have := Classical.choose_spec hS; simp_all +decide [ sum_f, sum_inv ] ;
          refine' ne_of_lt ( lt_of_le_of_lt ( Finset.sum_nonpos _ ) _ );
          · intro i hi; specialize hx''; replace hx'' := hx''.symm ▸ Finset.single_le_sum ( fun x _ => Nat.zero_le ( f_poly a b c x ) ) hi; simp_all +decide [ f_poly ] ;
            exact Nat.eq_zero_of_not_pos fun hi' => hx''.not_gt <| Nat.lt_of_lt_of_le ( Nat.mod_lt _ <| by linarith ) <| by nlinarith [ pow_pos hi' c ] ;
          · (expose_names; exact h_S_pos (Classical.choose hS) this);
      · linarith;
      · refine le_trans ‹_› ?_;
        gcongr;
        · exact mul_nonneg ( sub_nonneg_of_le ( one_le_pow₀ ( by norm_cast; linarith ) ) ) ( Nat.cast_nonneg _ );
        · exact sub_nonneg_of_le ( one_le_pow₀ ( by linarith ) )

/-
Properties of the sequences X_k and r_k.
-/
lemma seq_properties {a b c : ℕ} {S : Set ℚ} {Q : Finset ℕ → Prop} {m s : ℕ} {beta : S → Fin (m^c) → ℚ} {A_fam : S → Fin (m^c) → Finset ℕ} {M L X r : ℕ} (h : MetaAssumptions a b c S Q m s beta A_fam M L X r) (hS : S.Nonempty) :
  let r_seq := r_seq_def r s
  let X_seq := X_seq_def a b c m s M r X
  (s > 0) ∧
  (∀ k, r_seq k ≥ r) ∧
  (∀ k, 0 < X_seq k) ∧
  (∀ k, X_seq k < X_seq (k + 1)) ∧
  (∀ k, X_seq (k + 1) ≤ m^c * X_seq k + a * M) := by
    have h_X_seq_lt : ∀ k, X_seq_def a b c m s M r X k < Int.toNat (Y_val a b c m s M (X_seq_def a b c m s M r X k) (r_seq_def r s k)) := by
      intro k
      have h_Y_bounds : (X_seq_def a b c m s M r X k : ℤ) < Y_val a b c m s M (X_seq_def a b c m s M r X k) (r_seq_def r s k) := by
        have := Y_bounds ( show MetaAssumptions a b c S Q m s beta A_fam M L ( X_seq_def a b c m s M r X k ) ( r_seq_def r s k ) from ?_ ) hS
        generalize_proofs at *
        · exact this.1
        · induction' k with k ih
          · convert h using 1
            unfold r_seq_def; norm_num
          · constructor
            all_goals (try (first
              | exact h.h_pos_coeff
              | exact h.h_coprime_ab
              | exact h.h_c_pos
              | exact (fun q a_1 => h.h_S_pos q a_1)
              | exact h.h_s_div
              | exact h.h_m_ge_2
              | exact h.h_coprime_ma
              | exact (fun alpha i => h.h_A_pos alpha i)
              | exact h.h_six
              | exact (fun alpha i => h.h_M alpha i)
              | exact (fun alpha i => h.h_L alpha i)))
            case h_X_pos =>
              exact Nat.pos_of_ne_zero (by
                have hYb := Y_bounds ih hS
                exact ne_of_gt (by
                  linarith! [Int.toNat_of_nonneg (by linarith : 0 ≤ Y_val a b c m s M (X_seq_def a b c m s M r X k) (r_seq_def r s k))]))
            case h_r_pos =>
              have := h.h_r_pos
              unfold r_seq_def at *
              omega
            case h_ineq =>
              have h_iq := ih.h_ineq
              refine le_trans h_iq ?_
              gcongr
              · exact mul_nonneg (sub_nonneg_of_le (one_le_pow₀ (mod_cast h.h_m_ge_2.trans' (by norm_num)))) (Nat.cast_nonneg _)
              · exact sub_nonneg_of_le (one_le_pow₀ (mod_cast h.h_m_ge_2.trans' (by norm_num)))
              · exact Nat.add_le_add_left (Nat.mul_le_mul_right _ (Nat.le_succ _)) _
            case h_base_cases =>
              intro alpha n hn₁ hn₂ hn₃
              have hred := reduction_lemma
                (show MetaAssumptions a b c S Q m s beta A_fam M L (X_seq_def a b c m s M r X k) (r_seq_def r s k) from ih) hS
              convert hred alpha n _ _ _ using 1
              · unfold r_seq_def; ring_nf
              · exact le_trans (Int.self_le_toNat _) (mod_cast hn₁)
              · convert Int.ofNat_le.mpr hn₂ using 1
                norm_num [Y_val]
                exact Or.inl (by
                  rw [show X_seq_def a b c m s M r X (k + 1) = Int.toNat (Y_val a b c m s M (X_seq_def a b c m s M r X k) (r_seq_def r s k)) from rfl]
                  rw [Int.toNat_of_nonneg (by linarith [Y_bounds ih hS])]
                  unfold Y_val; ring)
              · convert hn₃ using 1; push_cast [r_seq_def]; ring
      generalize_proofs at *
      exact (by
        linarith [Int.self_le_toNat (Y_val a b c m s M (X_seq_def a b c m s M r X k) (r_seq_def r s k))])
    have h_X_seq_bounded : ∀ k, Int.toNat (Y_val a b c m s M (X_seq_def a b c m s M r X k) (r_seq_def r s k)) ≤ (m^c : ℕ) * X_seq_def a b c m s M r X k + a * M := by
      intros k
      apply Nat.le_of_lt_succ
      have := Y_bounds h hS
      simp_all +decide [Y_val]
      nlinarith [show (r_seq_def r s k : ℤ) * (m ^ c - 1) ≥ (r : ℤ) * (m ^ c - 1) by
        exact mul_le_mul_of_nonneg_right (mod_cast Nat.le_add_right _ _)
          (sub_nonneg_of_le <| mod_cast Nat.one_le_pow _ _ <| by linarith [h.h_m_ge_2])]
    refine' ⟨Nat.pos_of_ne_zero _, _, _, _, _⟩
    · intro hs_zero
      have h_contra : ∀ alpha : S, ∀ i : Fin (m^c), sum_pow c (A_fam alpha i) = 0 := by
        have := h.h_six.prop3; aesop
      have h_contra' : ∀ alpha : S, ∀ i : Fin (m^c), i.val = 0 := by
        intros alpha i
        have h_sum_zero : sum_pow c (A_fam alpha i) = 0 := h_contra alpha i
        have h_mod : Nat.ModEq (m^c) (sum_pow c (A_fam alpha i)) i.val :=
          h.h_six.prop2 alpha i
        have h_i_zero : i.val = 0 :=
          Nat.eq_zero_of_dvd_of_lt (Nat.dvd_of_mod_eq_zero <|
            h_mod.symm ▸ h_sum_zero.symm ▸ Nat.mod_eq_zero_of_dvd (dvd_zero _)) i.2
            |> fun h => by simp [h]
        exact h_i_zero
      have h_contra'' : m^c = 1 := by
        contrapose! h_contra'
        exact ⟨⟨hS.some, hS.choose_spec⟩,
               ⟨1, Nat.one_lt_iff_ne_zero_and_ne_one.mpr
                 ⟨by linarith [h.h_m_ge_2, pow_pos (zero_lt_two.trans_le h.h_m_ge_2) c],
                  h_contra'⟩⟩,
               by norm_num⟩
      have h_contra''' : m = 1 := by cases h; aesop
      have h_contra'''' : 2 ≤ m := h.h_m_ge_2
      linarith [h_contra'''']
    · exact fun k => Nat.le_add_right _ _
    · intro k
      exact Nat.recOn k
        (by have := h.h_X_pos; aesop)
        (fun k _ => lt_of_le_of_lt (Nat.zero_le _) (h_X_seq_lt k))
    · exact fun k => h_X_seq_lt k
    · exact fun k => h_X_seq_bounded k

/-
Proof of the meta theorem.
-/
theorem meta_theorem (a b c : ℕ) (S : Set ℚ) (Q : Finset ℕ → Prop) (m s : ℕ) (beta : S → Fin (m^c) → ℚ) (A_fam : S → Fin (m^c) → Finset ℕ) (M L X r : ℕ) :
  MetaTheoremStatement a b c S Q m s beta A_fam M L X r := by
    by_contra h;
    obtain ⟨h₁, h₂⟩ : ∃ h : MetaAssumptions a b c S Q m s beta A_fam M L X r, ∃ alpha : S, ∃ n : ℕ, X ≤ n ∧ n ≡ b * r [MOD a] ∧ ¬∃ A : Finset ℕ, Q A ∧ sum_f a b c A = n ∧ sum_inv A = alpha := by
      unfold MetaTheoremStatement at h; aesop;
    -- Let's obtain the sequences X_k and r_k from the assumptions.
    obtain ⟨r_seq, X_seq, hr_seq, hX_seq⟩ : ∃ (r_seq : ℕ → ℕ) (X_seq : ℕ → ℕ), r_seq 0 = r ∧ X_seq 0 = X ∧ (∀ k, r_seq (k + 1) = r_seq k + s) ∧ (∀ k, X_seq (k + 1) = Int.toNat (Y_val a b c m s M (X_seq k) (r_seq k))) ∧ (∀ k, 0 < X_seq k) ∧ (∀ k, X_seq k < X_seq (k + 1)) ∧ (∀ k, X_seq (k + 1) ≤ m^c * X_seq k + a * M) := by
      use fun k => r + k * s, fun k => Nat.rec X (fun k x_k => Int.toNat (Y_val a b c m s M x_k (r + k * s))) k;
      have := seq_properties h₁ (by
      exact ⟨ _, h₂.choose.2 ⟩);
      simp_all +decide [ add_mul, add_assoc ];
      unfold X_seq_def at *; aesop;
    -- By induction, we can show that for all k, solutions exist in the interval [X_k, m^c X_k + a M] for r_k.
    have h_ind : ∀ k, ∀ (alpha : S) (n : ℕ), X_seq k ≤ n → n ≤ m^c * X_seq k + a * M → n ≡ b * r_seq k [MOD a] → ∃ A : Finset ℕ, Q A ∧ A.card = r_seq k ∧ sum_f a b c A = n ∧ sum_inv A = alpha := by
      intro k;
      induction' k with k ih;
      · have := h₁.h_base_cases; aesop;
      · intro alpha n hn₁ hn₂ hn₃;
        have := step_reduction_lemma h₁ (by
        exact ⟨ _, alpha.2 ⟩) (X_seq k) (r_seq k) (by
        exact Nat.recOn k ( by linarith ) fun k ih => by linarith [ hX_seq.2.1 k ] ;) (by
        exact ih);
        simp_all +decide [ Nat.ModEq ];
        convert this alpha alpha.2 n hn₁ _ hn₃ using 1;
        convert hn₂ using 1;
        rw [ ← @Nat.cast_le ℤ ] ; norm_num;
        rw [ max_eq_left ];
        exact le_of_not_gt fun h => by have := hX_seq.2.2.2.2.1 k; linarith [ hX_seq.2.2.1 k, Int.toNat_of_nonpos h.le ] ;
    obtain ⟨alpha, n, hn₁, hn₂, hn₃⟩ := h₂;
    -- Choose k such that X_k ≤ n < X_{k+1}.
    obtain ⟨k, hk⟩ : ∃ k, X_seq k ≤ n ∧ n < X_seq (k + 1) := by
      -- Since $X_seq$ is strictly increasing and unbounded, there exists some $k$ such that $X_seq k > n$.
      obtain ⟨k, hk⟩ : ∃ k, X_seq k > n := by
        exact ⟨ n + 1, Nat.recOn n ( by linarith [ hX_seq.2.2.2.1 0, hX_seq.2.2.2.2.1 0 ] ) fun n ihn => by linarith [ hX_seq.2.2.2.1 ( n + 1 ), hX_seq.2.2.2.2.1 ( n + 1 ) ] ⟩;
      induction' k with k ih;
      · linarith;
      · exact if h : X_seq k > n then ih h else ⟨ k, le_of_not_gt h, hk ⟩;
    -- Since $n \equiv b * r \pmod{a}$ and $r_seq k = r + k * s$, we have $n \equiv b * r_seq k \pmod{a}$.
    have hn_mod : n ≡ b * r_seq k [MOD a] := by
      have hn_mod : a ∣ s := by
        exact h₁.h_s_div;
      have hn_mod : r_seq k ≡ r [MOD a] := by
        have hn_mod : ∀ k, r_seq k ≡ r [MOD a] := by
          intro k; induction k <;> simp_all +decide [ ← ZMod.natCast_eq_natCast_iff ] ;
          exact (ZMod.natCast_eq_zero_iff s a).mpr hn_mod;
        exact hn_mod k;
      exact hn₂.trans ( Nat.ModEq.mul_left _ hn_mod.symm );
    exact hn₃ <| by obtain ⟨ A, hA₁, hA₂, hA₃, hA₄ ⟩ := h_ind k alpha n hk.1 ( by linarith [ hX_seq.2.2.2.2.2 k ] ) hn_mod; exact ⟨ A, hA₁, hA₃, hA₄ ⟩ ;

#print axioms meta_theorem

/-
Structure capturing the assumptions for the corollary.
-/
structure CorollaryAssumptions (a b c : ℕ) (S : Set ℚ) (Q : Finset ℕ → Prop) (m s : ℕ)
  (beta : S → Fin (m^c) → ℚ) (A_fam : S → Fin (m^c) → Finset ℕ)
  (M L : ℕ) (X_map r_map : Fin a → ℕ) : Prop where
  h_pos_coeff : 0 < a ∧ 0 < b
  h_coprime_ab : a.Coprime b
  h_c_pos : 0 < c
  h_S_pos : ∀ q ∈ S, 0 < q
  h_s_div : a ∣ s
  h_m_ge_2 : 2 ≤ m
  h_coprime_ma : m.Coprime a
  h_A_pos : ∀ (alpha : S) (i : Fin (m^c)), is_positive_set (A_fam alpha i)
  h_six : SixProperties c S Q m s beta A_fam
  h_M : ∀ (alpha : S) (i : Fin (m^c)), sum_pow c (A_fam alpha i) ≤ M
  h_L : ∀ (alpha : S) (i : Fin (m^c)), L ≤ sum_pow c (A_fam alpha i)
  h_X_pos : ∀ w, 0 < X_map w
  h_r_pos : ∀ w, 0 < r_map w
  h_r_cong : ∀ w, r_map w * b ≡ w.val [MOD a]
  h_ineq : ∀ w, ((m^c : ℤ) - 1) * b * ((r_map w : ℤ) * ((m^c : ℤ) - 1) - s) ≥ a * ((M : ℤ) - L)
  h_base_cases : ∀ (w : Fin a) (alpha : S) (n : ℕ), X_map w ≤ n → n ≤ m^c * X_map w + a * M → n ≡ w.val [MOD a] →
    ∃ A, Q A ∧ A.card = r_map w ∧ sum_f a b c A = n ∧ sum_inv A = alpha

/-
Helper lemma: The corollary assumptions imply the meta assumptions for each $w$.
-/
lemma corollary_implies_meta_assumptions (a b c : ℕ) (S : Set ℚ) (Q : Finset ℕ → Prop) (m s : ℕ)
  (beta : S → Fin (m^c) → ℚ) (A_fam : S → Fin (m^c) → Finset ℕ)
  (M L : ℕ) (X_map r_map : Fin a → ℕ)
  (h : CorollaryAssumptions a b c S Q m s beta A_fam M L X_map r_map)
  (w : Fin a) :
  MetaAssumptions a b c S Q m s beta A_fam M L (X_map w) (r_map w) := by
    obtain ⟨h_pos_coeff, h_coprime_ab, h_c_pos, h_S_pos, h_s_div, h_m_ge_2, h_coprime_ma, h_A_pos, h_six, h_M, h_L, h_X_pos, h_r_pos, h_r_cong, h_ineq, h_base_cases⟩ := h;
    constructor;
    any_goals tauto;
    intro alpha n hn₁ hn₂ hn₃; specialize h_base_cases w alpha n hn₁ hn₂; simp_all +decide [ mul_comm, Nat.ModEq ] ;

/-
Helper lemma: If $n \ge X_w$ and $n \equiv w \pmod a$, then a solution exists.
-/
lemma exists_solution_of_ge_X_map (a b c : ℕ) (S : Set ℚ) (Q : Finset ℕ → Prop) (m s : ℕ)
  (beta : S → Fin (m^c) → ℚ) (A_fam : S → Fin (m^c) → Finset ℕ)
  (M L : ℕ) (X_map r_map : Fin a → ℕ)
  (h : CorollaryAssumptions a b c S Q m s beta A_fam M L X_map r_map)
  (alpha : S) (n : ℕ)
  (w : Fin a) (hw : n ≡ w.val [MOD a]) (hn : n ≥ X_map w) :
  ∃ A, Q A ∧ sum_f a b c A = n ∧ sum_inv A = alpha := by
    have := h.h_r_cong w; simp_all +decide [ Nat.ModEq ] ;
    -- Apply the corollary_implies_meta_assumptions lemma to obtain the meta assumptions for $X_w$ and $r_w$.
    have h_meta : MetaAssumptions a b c S Q m s beta A_fam M L (X_map w) (r_map w) := by
      convert corollary_implies_meta_assumptions a b c S Q m s beta A_fam M L X_map r_map h w using 1
    generalize_proofs at *; (
    -- Apply the meta theorem to obtain the solution.
    have := meta_theorem a b c S Q m s beta A_fam M L (X_map w) (r_map w);
    simp_all +decide [ MetaTheoremStatement ] ; (
    exact this _ alpha.2 _ hn ( by simpa [ mul_comm, Nat.ModEq, Nat.mul_mod ] using hw.trans ( Eq.symm ‹r_map w * b % a = ↑w % a› ) ) |> fun ⟨ A, hA₁, hA₂, hA₃ ⟩ => ⟨ A, hA₁, hA₂, hA₃ ⟩ ;);)

/-
Corollary: Under the assumptions (and assuming Q implies positivity), $n_0(f(x), \alpha) \le \max_w X_w$.
-/
theorem meta_corollary (a b c : ℕ) (S : Set ℚ) (Q : Finset ℕ → Prop) (m s : ℕ)
  (beta : S → Fin (m^c) → ℚ) (A_fam : S → Fin (m^c) → Finset ℕ)
  (M L : ℕ) (X_map r_map : Fin a → ℕ)
  (h : CorollaryAssumptions a b c S Q m s beta A_fam M L X_map r_map)
  (h_Q_pos : ∀ A, Q A → is_positive_set A) :
  ∀ alpha ∈ S, n_0 a b c alpha ≤ Finset.univ.sup X_map := by
    -- Let $K = \sup_w X_w$.
    set K := Finset.sup Finset.univ X_map;
    -- We need to show that $K \in n_0\_set(a, b, c, \alpha)$.
    have h_K_in_n0 : ∀ alpha ∈ S, K ∈ n_0_set a b c alpha := by
      intro alpha halpha
      intro n hn
      have hn_ge_Xw : ∃ w : Fin a, n ≥ X_map w ∧ n ≡ w.val [MOD a] := by
        rcases a with ( _ | _ | a ) <;> simp_all +decide [ Nat.ModEq ];
        · cases h ; aesop;
        · exact ⟨ le_trans ( Finset.le_sup ( f := X_map ) ( Finset.mem_univ 0 ) ) hn, Nat.mod_one _ ⟩;
        · exact ⟨ ⟨ n % ( a + 1 + 1 ), Nat.mod_lt _ ( Nat.succ_pos _ ) ⟩, le_trans ( Finset.le_sup ( f := X_map ) ( Finset.mem_univ _ ) ) hn, by simp +decide ⟩;
      obtain ⟨ w, hw₁, hw₂ ⟩ := hn_ge_Xw;
      have := exists_solution_of_ge_X_map a b c S Q m s beta A_fam M L X_map r_map h;
      exact Exists.elim ( this ⟨ alpha, halpha ⟩ n w hw₂ hw₁ ) fun A hA => ⟨ A, h_Q_pos A hA.1, hA.2.1, hA.2.2 ⟩;
    exact fun alpha halpha => Nat.sInf_le <| h_K_in_n0 alpha halpha

/-
Assumptions for the General Meta Theorem.
-/
structure GeneralMetaTheoremAssumptions (a b c : ℕ) (S : Set ℚ) (Q : Finset ℕ → Prop) (m s : ℕ)
  (beta : S → Fin (m^c) → ℚ) (A_fam : S → Fin (m^c) → Finset ℕ)
  (M L : ℕ) (l : ℕ) (X_map r_map : Fin a → ℕ) : Prop where
  h_pos_coeff : 0 < a ∧ 0 < b
  h_c_pos : 0 < c
  h_S_pos : ∀ q ∈ S, 0 < q
  h_s_div : a ∣ s
  h_m_ge_2 : 2 ≤ m
  h_coprime_ma : m.Coprime a
  h_A_pos : ∀ (alpha : S) (i : Fin (m^c)), is_positive_set (A_fam alpha i)
  h_six : SixProperties c S Q m s beta A_fam
  h_M : ∀ (alpha : S) (i : Fin (m^c)), sum_pow c (A_fam alpha i) ≤ M
  h_L : ∀ (alpha : S) (i : Fin (m^c)), L ≤ sum_pow c (A_fam alpha i)
  h_X_pos : ∀ w, 0 < X_map w
  h_r_pos : ∀ w, 0 < r_map w
  h_r_cong : ∀ w, r_map w * b ≡ w.val [MOD a]
  h_ineq : ∀ w, ((m^c : ℤ) - 1) * b * ((r_map w : ℤ) * ((m^c : ℤ) - 1) - s) ≥ a * ((M : ℤ) - L)
  h_base_cases : ∀ (w : Fin a) (alpha : S) (n : ℕ), X_map w ≤ n → n ≤ m^c * (X_map w + l * r_map w) + a * M → n ≡ w.val [MOD a] →
    ∃ A, Q A ∧ A.card = r_map w ∧ sum_f a b c A = n ∧ sum_inv A = alpha

/-
General Meta Theorem: Under the generalized assumptions, for any $j \le l$ with $b+j$ coprime to $a$, $n_0(f_j, \alpha) \le \max_w (X_w + j r_w)$.
-/
theorem general_meta_theorem (a b c : ℕ) (S : Set ℚ) (Q : Finset ℕ → Prop) (m s : ℕ)
  (beta : S → Fin (m^c) → ℚ) (A_fam : S → Fin (m^c) → Finset ℕ)
  (M L : ℕ) (l : ℕ) (X_map r_map : Fin a → ℕ)
  (h : GeneralMetaTheoremAssumptions a b c S Q m s beta A_fam M L l X_map r_map)
  (h_Q_pos : ∀ A, Q A → is_positive_set A) :
  ∀ (j : ℕ), j ≤ l → (b + j).Coprime a →
    ∀ (alpha : S), n_0 a (b + j) c alpha ≤ Finset.univ.sup (fun w => X_map w + j * r_map w) := by
      intro j hj hj' alpha;
      -- Let $\pi(w) = w + j r_w \pmod a$. Since $\gcd(b+j, a) = 1$, $\pi$ is a bijection.
      obtain ⟨pi, hpi⟩ : ∃ pi : Fin a ≃ Fin a, ∀ w : Fin a, (w + j * r_map w : ℕ) ≡ pi w [MOD a] := by
        have h_pi_bij : ∀ w₁ w₂ : Fin a, (w₁ + j * r_map w₁ : ℕ) ≡ (w₂ + j * r_map w₂ : ℕ) [MOD a] → w₁ = w₂ := by
          intro w₁ w₂ h_cong
          have h_eq : (w₁ : ℕ) ≡ (w₂ : ℕ) [MOD a] := by
            have h_eq : (r_map w₁ * b : ℕ) ≡ w₁ [MOD a] ∧ (r_map w₂ * b : ℕ) ≡ w₂ [MOD a] := by
              exact ⟨ by simpa [ mul_comm ] using h.h_r_cong w₁, by simpa [ mul_comm ] using h.h_r_cong w₂ ⟩;
            have h_eq : (r_map w₁ * (b + j) : ℕ) ≡ (r_map w₂ * (b + j) : ℕ) [MOD a] := by
              simp_all +decide [ ← ZMod.natCast_eq_natCast_iff, mul_add ] ; ring_nf at * ; aesop;
            generalize_proofs at *; (
            have h_eq : r_map w₁ ≡ r_map w₂ [MOD a] := by
              rw [ Nat.modEq_iff_dvd ] at *;
              simp_all +decide [ ← sub_mul ];
              exact Int.dvd_of_dvd_mul_left_of_gcd_one h_eq ( by simpa [ Int.gcd_natCast_natCast ] using hj'.symm )
            generalize_proofs at *; (
            simp_all +decide [ ← ZMod.natCast_eq_natCast_iff ]))
          generalize_proofs at *; exact Fin.ext (Nat.mod_eq_of_lt w₁.2 ▸ Nat.mod_eq_of_lt w₂.2 ▸ h_eq) ;
        have h_pi_bij : Function.Bijective (fun w : Fin a => ⟨(w + j * r_map w) % a, Nat.mod_lt _ (Nat.pos_of_ne_zero (by
        exact Nat.ne_of_gt ( Fin.pos w )))⟩ : Fin a → Fin a) := by
          exact ⟨ fun w₁ w₂ h => h_pi_bij _ _ <| by simpa [ Nat.ModEq, Nat.mod_eq_of_lt ] using congr_arg Fin.val h, Finite.injective_iff_surjective.mp <| fun w₁ w₂ h => h_pi_bij _ _ <| by simpa [ Nat.ModEq, Nat.mod_eq_of_lt ] using congr_arg Fin.val h ⟩
        generalize_proofs at *;
        exact ⟨ Equiv.ofBijective _ h_pi_bij, fun w => by simp +decide [ Nat.ModEq ] ⟩;
      -- By the meta corollary, we have $n_0(f_j, \alpha) \le \max_w (X_{\pi^{-1}(w)} + j r_{\pi^{-1}(w)})$.
      have h_meta_corollary : ∀ alpha : S, n_0 a (b + j) c alpha ≤ Finset.univ.sup (fun w => X_map (pi.symm w) + j * r_map (pi.symm w)) := by
        intro alpha
        apply meta_corollary a (b + j) c S Q m s beta A_fam M L (fun w => X_map (pi.symm w) + j * r_map (pi.symm w)) (fun w => r_map (pi.symm w));
        · constructor;
          exact ⟨ h.h_pos_coeff.1, by linarith [ h.h_pos_coeff.2 ] ⟩;
          exact hj'.symm;
          exact h.h_c_pos;
          exact h.h_S_pos;
          exact h.h_s_div;
          exact h.h_m_ge_2;
          exact h.h_coprime_ma;
          exact h.h_A_pos;
          exact h.h_six;
          exact h.h_M;
          exact h.h_L;
          · exact fun w => add_pos_of_pos_of_nonneg ( h.h_X_pos _ ) ( Nat.zero_le _ );
          · exact fun w => h.h_r_pos _;
          · intro w; specialize hpi ( pi.symm w ) ; simp_all +decide [ ← ZMod.natCast_eq_natCast_iff, mul_comm ] ;
            have := h.h_r_cong ( pi.symm w ) ; simp_all +decide [ ← ZMod.natCast_eq_natCast_iff ] ;
            linear_combination' this + hpi;
          · intro w;
            have := h.h_ineq ( pi.symm w );
            refine le_trans this ?_;
            gcongr ; norm_num;
            · have := h.h_ineq ( pi.symm w );
              contrapose! this;
              refine' lt_of_lt_of_le ( mul_neg_of_pos_of_neg _ _ ) _;
              · exact mul_pos ( sub_pos.mpr ( one_lt_pow₀ ( mod_cast h.h_m_ge_2 ) ( by linarith [ h.h_c_pos ] ) ) ) ( Nat.cast_pos.mpr ( h.h_pos_coeff.2 ) );
              · linarith;
              · exact mul_nonneg ( Nat.cast_nonneg _ ) ( sub_nonneg_of_le ( mod_cast h.h_L alpha ( Fin.mk 0 ( by linarith [ h.h_m_ge_2, pow_pos ( zero_lt_two.trans_le h.h_m_ge_2 ) c ] ) ) |> le_trans <| h.h_M alpha ( Fin.mk 0 ( by linarith [ h.h_m_ge_2, pow_pos ( zero_lt_two.trans_le h.h_m_ge_2 ) c ] ) ) ) );
            · exact sub_nonneg_of_le ( one_le_pow₀ ( mod_cast h.h_m_ge_2.trans' ( by norm_num ) ) );
            · grind;
          · intro w alpha n hn₁ hn₂ hn₃;
            have := h.h_base_cases ( pi.symm w ) alpha ( n - j * r_map ( pi.symm w ) ) ?_ ?_ ?_ <;> simp_all +decide [ Nat.ModEq ];
            · obtain ⟨ A, hA₁, hA₂, hA₃, hA₄ ⟩ := this; use A; simp_all +decide [ sum_f ] ;
              unfold f_poly at *; simp_all +decide [Finset.sum_add_distrib] ;
              linarith [ Nat.sub_add_cancel ( by nlinarith : j * r_map ( pi.symm w ) ≤ n ) ];
            · exact le_tsub_of_add_le_right hn₁;
            · nlinarith [ Nat.zero_le ( m ^ c * r_map ( pi.symm w ) ) ];
            · zify at *;
              rw [ Nat.cast_sub ];
              · simp_all +decide [ ← ZMod.intCast_eq_intCast_iff' ];
                grind;
              · grind;
        · assumption;
        · exact alpha.2;
      exact le_trans ( h_meta_corollary alpha ) ( Finset.sup_le fun w hw => Finset.le_sup ( f := fun w => X_map w + j * r_map w ) ( Finset.mem_univ ( pi.symm w ) ) )

#print axioms general_meta_theorem
