/-
Below you can find a formalization of the first two theorems in my paper 'The binomial case of Graham's conjecture on polynomial representations with prescribed sum of reciprocals'. The paper can be found on my GitHub;

https://github.com/Woett/A-normal-paper-is-probably-fine/blob/main/The%20binomial%20case%20of%20Graham's%20conjecture%20on%20polynomial%20representations%20with%20prescribed%20sum%20of%20reciprocals.pdf

This formalization was generated by Aristotle from Harmonic (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365
-/

import Mathlib

open Finset BigOperators

/-- Sum of d-th powers of elements of A -/
def sumPow (A : Finset ℕ) (d : ℕ) : ℤ :=
  ∑ x ∈ A, (x : ℤ) ^ d

/-- Sum of reciprocals of elements of A -/
def sumRecip (A : Finset ℕ) : ℚ :=
  ∑ x ∈ A, ((x : ℚ))⁻¹

/-- f(x) = a * x^d + b, summed over A. Equals a * sumPow A d + b * |A| -/
def sumF (a b : ℤ) (d : ℕ) (A : Finset ℕ) : ℤ :=
  a * sumPow A d + b * (A.card : ℤ)

open Classical in
/-- Definition of n₀(f, α) -/
noncomputable def n₀ (f : ℕ → ℤ) (α : ℚ) : WithTop ℤ :=
  let S := {N : ℤ | ∀ n : ℤ, N ≤ n →
    ∃ A : Finset ℕ, (∀ x ∈ A, 0 < x) ∧ (∑ x ∈ A, f x) = n ∧ sumRecip A = α}
  if S.Nonempty ∧ BddBelow S then ↑(sInf S) else ⊤

/-- Scale each element of A by m -/
def mFinset (m : ℕ) (A : Finset ℕ) : Finset ℕ :=
  A.image (· * m)

/-- U_k = b * (r + k*s) * (m^d - 1) - b * s -/
def Uk (b : ℤ) (r s : ℕ) (md : ℤ) (k : ℕ) : ℤ :=
  b * ((r : ℤ) + (k : ℤ) * (s : ℤ)) * (md - 1) - b * (s : ℤ)

/-- Y_k sequence: Y_0 = X, Y_{k+1} = m^d * Y_k + aL - U_k -/
def Yk (X a L b : ℤ) (r s : ℕ) (md : ℤ) : ℕ → ℤ
  | 0 => X
  | k + 1 => md * Yk X a L b r s md k + a * L - Uk b r s md k

/-- Z_k sequence: Z_0 = m^dX + aM, Z_{k+1} = md * Z_k + aM - U_k -/
def Zk (X a M b : ℤ) (r s : ℕ) (md : ℤ) : ℕ → ℤ
  | 0 => md * X + a * M
  | k + 1 => md * Zk X a M b r s md k + a * M - Uk b r s md k

/-- T = a(M - L) / (m^d - 1), the tolerance parameter in the base case bounds. -/
noncomputable def baseTolerance (a L M : ℤ) (m : ℕ) (d : ℕ) : ℚ :=
  (a : ℚ) * ((M : ℚ) - (L : ℚ)) / ((↑m : ℚ) ^ d - 1)

lemma sumF_eq_sum (a c : ℤ) (d : ℕ) (A : Finset ℕ) :
    sumF a c d A = ∑ x ∈ A, (a * (x : ℤ) ^ d + c) := by
  unfold sumF sumPow
  simp [Finset.mul_sum, Finset.sum_add_distrib, Finset.sum_const]
  ring

lemma card_mFinset {m : ℕ} (hm : 0 < m) (A : Finset ℕ) :
    (mFinset m A).card = A.card := by
  exact Finset.card_image_of_injective _ fun x y hxy => mul_right_cancel₀ hm.ne' hxy

lemma sumPow_mFinset {m : ℕ} (hm : 0 < m) (A : Finset ℕ) (d : ℕ) :
    sumPow (mFinset m A) d = (m : ℤ) ^ d * sumPow A d := by
  simp only [sumPow, mFinset]
  rw [Finset.sum_image]
  · simp only [Nat.cast_mul, mul_pow, mul_comm ((m : ℤ) ^ d)]
    rw [← Finset.sum_mul]
  · intro x _ y _ hxy
    exact mul_right_cancel₀ hm.ne' hxy

lemma sumF_union {A B : Finset ℕ} (h : Disjoint A B) (a b : ℤ) (d : ℕ) :
    sumF a b d (A ∪ B) = sumF a b d A + sumF a b d B := by
  unfold sumF sumPow; simp +decide [ *, Finset.sum_union ] ; ring;

lemma sumF_mFinset {m : ℕ} (hm : 0 < m) (a b : ℤ) (d : ℕ) (A : Finset ℕ) :
    sumF a b d (mFinset m A) =
      (m : ℤ) ^ d * sumF a b d A - b * ((m : ℤ) ^ d - 1) * (A.card : ℤ) := by
  simp only [sumF, sumPow_mFinset hm, card_mFinset hm]
  ring

lemma sumRecip_union {A B : Finset ℕ} (h : Disjoint A B) :
    sumRecip (A ∪ B) = sumRecip A + sumRecip B := by
  unfold sumRecip; rw [ Finset.sum_union h ] ;

lemma sumRecip_mFinset {m : ℕ} (hm : 0 < m) (A : Finset ℕ) :
    sumRecip (mFinset m A) = sumRecip A / (m : ℚ) := by
  unfold sumRecip mFinset;
  rcases eq_or_ne m 0 with h | h <;> simp_all +decide [ div_eq_inv_mul, Finset.mul_sum _ _ _ ]

lemma mFinset_pos {m : ℕ} (hm : 0 < m) {A : Finset ℕ} (hA : ∀ x ∈ A, 0 < x) :
    ∀ x ∈ mFinset m A, 0 < x := by
  intro x hx
  simp only [mFinset, Finset.mem_image] at hx
  obtain ⟨y, hy, rfl⟩ := hx
  exact Nat.mul_pos (hA y hy) hm

lemma Int.gcd_pow_right {a : ℤ} {m : ℕ} (h : Int.gcd a m = 1) (d : ℕ) :
    Int.gcd a ((m : ℤ) ^ d) = 1 := by
  exact Int.gcd_pow_right_of_gcd_eq_one h

lemma exists_fin_residue {a : ℤ} {md : ℕ} (hmd : 0 < md)
    (hcop : Int.gcd a (md : ℤ) = 1) (n : ℤ) :
    ∃ i : Fin md, (md : ℤ) ∣ (n - a * ↑i.val) := by
  obtain ⟨x, hx⟩ : ∃ x : ℤ, a * x ≡ 1 [ZMOD md] := by
    have := Int.gcd_eq_gcd_ab a md; aesop;
  obtain ⟨i, hi⟩ : ∃ i : ℤ, a * i ≡ n [ZMOD md] := by
    exact ⟨ x * n, by simpa [ mul_assoc ] using hx.mul_right n ⟩
  use ⟨Int.toNat (i % md), by
    linarith [ Int.emod_lt_of_pos i ( by positivity : 0 < ( md : ℤ ) ), Int.toNat_of_nonneg ( Int.emod_nonneg i ( by positivity : ( md : ℤ ) ≠ 0 ) ) ]⟩
  generalize_proofs at *;
  simp_all +decide [ ← ZMod.intCast_zmod_eq_zero_iff_dvd, Int.emod_nonneg _ ( by positivity : ( md : ℤ ) ≠ 0 ) ];
  simp_all +decide [ ← ZMod.intCast_eq_intCast_iff ]

lemma Yk_succ_le_Zk (X a L M b : ℤ) (r s : ℕ) (md : ℤ)
    (hmd : 2 ≤ md)
    (hLM : L ≤ M)
    (ineq1a : 0 ≤ b * ↑r * (md - 1) - b * ↑s + a * (M - L))
    (ineq1b : 0 ≤ b * ↑s * (md - 1) + a * (M - L))
    (k : ℕ) :
    Yk X a L b r s md (k + 1) ≤ Zk X a M b r s md k := by
  induction' k with k ih generalizing X a L M b r s md <;> norm_num at *;
  · exact show md * X + a * L - ( b * ( r + 0 * s ) * ( md - 1 ) - b * s ) ≤ md * X + a * M from by linarith;
  · have hYk_succ : Yk X a L b r s md (k + 2) = md * Yk X a L b r s md (k + 1) + a * L - Uk b r s md (k + 1) := by
      rfl
    have hZk_succ : Zk X a M b r s md (k + 1) = md * Zk X a M b r s md k + a * M - Uk b r s md k := by
      rfl;
    specialize ih X a L M b r s md hmd hLM ineq1a ineq1b;
    unfold Uk at *;
    push_cast at *; nlinarith;

lemma n₀_le (f : ℕ → ℤ) (α : ℚ) (B : ℤ)
    (hB : ∀ n : ℤ, B ≤ n →
      ∃ A : Finset ℕ, (∀ x ∈ A, 0 < x) ∧ (∑ x ∈ A, f x) = n ∧ sumRecip A = α)
    (hBdd : BddBelow {N : ℤ | ∀ n : ℤ, N ≤ n →
      ∃ A : Finset ℕ, (∀ x ∈ A, 0 < x) ∧ (∑ x ∈ A, f x) = n ∧ sumRecip A = α}) :
    n₀ f α ≤ ↑B := by
  unfold n₀
  rw [if_pos ⟨⟨B, hB⟩, hBdd⟩]
  exact WithTop.coe_le_coe.mpr (csInf_le hBdd hB)

/-- sumPow A d = ∑ x ∈ A, (x : ℤ)^d. Each x is a natural number, so (x : ℤ)^d ≥ 0. -/
lemma sumPow_nonneg (A : Finset ℕ) (d : ℕ) : 0 ≤ sumPow A d := by
  exact Finset.sum_nonneg fun _ _ => by positivity;

/-- For a > 0, d ≥ 1, and A a finset of positive naturals, ∑(a*x^d + c) ≥ -c². -/
lemma sum_poly_bdd_below (a : ℤ) (ha : 0 < a) (c : ℤ) (d : ℕ) (hd : 0 < d)
    (A : Finset ℕ) (hA : ∀ x ∈ A, 0 < x) :
    -(c ^ 2) ≤ ∑ x ∈ A, (a * (↑x : ℤ) ^ d + c) := by
  norm_num [ Finset.sum_add_distrib ];
  -- Let's consider the two cases: $c \geq 0$ and $c < 0$.
  by_cases hc : c ≥ 0;
  · exact le_trans ( neg_nonpos_of_nonneg ( sq_nonneg _ ) ) ( add_nonneg ( Finset.sum_nonneg fun _ _ => mul_nonneg ha.le ( pow_nonneg ( Nat.cast_nonneg _ ) _ ) ) ( mul_nonneg ( Nat.cast_nonneg _ ) hc ) );
  · -- For each $x \in A$, if $a * x^d + c < 0$, then $x^d < -c / a \leq -c$ (since $a \geq 1$).
    have h_bad_elements : ∀ x ∈ A, a * x ^ d + c < 0 → x < Int.natAbs c := by
      intro x hx hx'; cases abs_cases c <;> nlinarith [ pow_le_pow_right₀ ( show 1 ≤ ( x : ℤ ) by linarith [ hA x hx ] ) hd ] ;
    -- Since $a * x^d + c < 0$ implies $x < \text{Int.natAbs } c$, there are at most $\text{Int.natAbs } c - 1$ such elements in $A$.
    have h_card_bad_elements : (Finset.filter (fun x : ℕ => a * x ^ d + c < 0) A).card ≤ Int.natAbs c - 1 := by
      exact le_trans ( Finset.card_le_card fun x hx => Finset.mem_Ico.mpr ⟨ hA x ( Finset.filter_subset _ _ hx ), h_bad_elements x ( Finset.filter_subset _ _ hx ) ( Finset.mem_filter.mp hx |>.2 ) ⟩ ) ( by simp );
    -- Each bad element contributes at least $c$ to the sum, so the total contribution from bad elements is at least $(\text{Int.natAbs } c - 1) * c$.
    have h_contribution_bad_elements : ∑ x ∈ A, (a * x ^ d + c) ≥ ∑ x ∈ A.filter (fun x : ℕ => a * x ^ d + c < 0), c := by
      rw [ Finset.sum_filter ];
      gcongr ; aesop;
    simp_all +decide [ Finset.sum_add_distrib ];
    nlinarith [ abs_of_neg hc, Nat.sub_add_cancel ( show 1 ≤ Int.natAbs c from Int.natAbs_pos.mpr hc.ne ) ]

/-- The set of thresholds N (where every n ≥ N is representable) is bounded below. -/
lemma bdd_below_poly_threshold (a : ℤ) (ha : 0 < a) (c : ℤ) (d : ℕ) (hd : 0 < d) (α : ℚ) :
    BddBelow {N : ℤ | ∀ n : ℤ, N ≤ n →
      ∃ A : Finset ℕ, (∀ x ∈ A, 0 < x) ∧
        (∑ x ∈ A, (fun x : ℕ => a * (↑x : ℤ) ^ d + c) x) = n ∧ sumRecip A = α} := by
  use -(c ^ 2)
  intro N hN
  obtain ⟨A, hApos, hAsum, _⟩ := hN N le_rfl
  rw [← hAsum]
  exact sum_poly_bdd_below a ha c d hd A hApos

/-- m^d * X + a * M ≥ X + a when m^d ≥ 2, X ≥ 0, and M ≥ 1. -/
lemma z0_ge_x_plus_a (X a M : ℤ) (md : ℤ)
    (hmd : 2 ≤ md) (hX : 0 ≤ X) (ha : 0 < a) (hM : 1 ≤ M) :
    md * X + a * M ≥ X + a := by
  nlinarith

/-- Any n ∈ [X, X + a - 1] is in the base range when X ≥ 0, md ≥ 2, M ≥ 1. -/
lemma interval_in_base_range (X a M L : ℤ) (md : ℤ)
    (hmd : 2 ≤ md) (hX : 0 ≤ X) (ha : 0 < a)
    (hLM : L ≤ M) (hM_pos : 1 ≤ M)
    (n : ℤ) (hn_lower : X ≤ n) (hn_upper : n ≤ X + a - 1) :
    (md - 1) * X - a * (M - L) ≤ (md - 1) * n ∧
    (md - 1) * n ≤ (md - 1) * (md * X + a * M) + a * (M - L) := by
  constructor
  · nlinarith [mul_le_mul_of_nonneg_left hn_lower (show (0 : ℤ) ≤ md - 1 by linarith),
               mul_nonneg ha.le (sub_nonneg.mpr hLM)]
  · have h1 : (md - 1) * n ≤ (md - 1) * (X + a - 1) :=
      mul_le_mul_of_nonneg_left hn_upper (by linarith)
    have h2 : (md - 1) * (X + a - 1) ≤ (md - 1) * (md * X + a * M) :=
      mul_le_mul_of_nonneg_left (by nlinarith) (by linarith)
    linarith [mul_nonneg ha.le (sub_nonneg.mpr hLM)]

/-- In any interval [X, X + a - 1] (with a ≥ 1), there exists n ≡ r (mod a). -/
lemma interval_has_residue (X a r : ℤ) (ha : 0 < a) :
    ∃ n, a ∣ n - r ∧ X ≤ n ∧ n ≤ X + a - 1 := by
  obtain ⟨q, k, hk⟩ : ∃ q k : ℤ, r - X = a * q + k ∧ 0 ≤ k ∧ k < a := by
    exact ⟨ ( r - X ) / a, ( r - X ) % a, by rw [ Int.mul_ediv_add_emod ], Int.emod_nonneg _ ha.ne', Int.emod_lt_of_pos _ ha ⟩;
  exact ⟨ X + k, ⟨ -q, by linarith ⟩, by linarith, by linarith ⟩

/-- The sequence W(k) := Z(k) - b*(r+ks) satisfies W(k+1) = md*W(k) + aM. -/
lemma Zk_tendsto_atTop (X a M b : ℤ) (r s : ℕ) (md : ℤ)
    (ha : 0 < a) (hmd : 2 ≤ md) (hM : 0 < M)
    (hZ0 : Zk X a M b r s md 0 > b * ((r : ℤ) + 0 * (s : ℤ))) :
    Filter.Tendsto (fun k => Zk X a M b r s md k) Filter.atTop Filter.atTop := by
  -- By induction, we can show that $W(k) \geq W(0) \cdot (md)^k$ where $W(0) = Z(0) - b(r+ks)$.
  have h_W_ge_exp : ∀ k, Zk X a M b r s md k - b * ((r : ℤ) + (k : ℤ) * (s : ℤ)) ≥ (Zk X a M b r s md 0 - b * (↑r + 0 * ↑s)) * (md : ℝ) ^ k := by
    intro k; norm_cast; induction' k with k ih <;> norm_num at *;
    rw [ pow_succ' ] ; rw [ show Zk X a M b r s md ( k + 1 ) = md * Zk X a M b r s md k + a * M - Uk b r s md k from rfl ] ; rw [ show Uk b r s md k = b * ( ( r : ℤ ) + ( k : ℤ ) * ( s : ℤ ) ) * ( md - 1 ) - b * ( s : ℤ ) from rfl ] ; nlinarith [ pow_pos ( by linarith : 0 < ( md : ℤ ) ) k ] ;
  -- Since $md \geq 2$, we know that $(md)^k$ grows exponentially, so $W(k)$ tends to infinity as $k$ tends to infinity.
  have h_W_inf : Filter.Tendsto (fun k => ((Zk X a M b r s md 0 - b * (↑r + 0 * ↑s)) : ℝ) * (md : ℝ) ^ k + b * ((r : ℝ) + (k : ℝ) * (s : ℝ))) Filter.atTop Filter.atTop := by
    -- Since $md \geq 2$, we know that $(md)^k$ grows exponentially, so $W(k)$ tends to infinity as $k$ tends to infinity. We can use the fact that $md^k$ grows faster than any linear function.
    have h_exp_growth : Filter.Tendsto (fun k => ((md : ℝ) ^ k) / k) Filter.atTop Filter.atTop := by
      have h_exp_growth : Filter.Tendsto (fun k => Real.exp (k * Real.log (md : ℝ)) / k) Filter.atTop Filter.atTop := by
        have := Real.tendsto_exp_div_pow_atTop 1;
        have := this.comp ( Filter.tendsto_id.atTop_mul_const ( Real.log_pos <| show ( md : ℝ ) > 1 by norm_cast ) );
        convert this.const_mul_atTop ( show 0 < Real.log ( md : ℝ ) by exact Real.log_pos <| by norm_cast ) using 2 ; norm_num ; ring_nf;
        exact eq_div_of_mul_eq ( ne_of_gt <| Real.log_pos <| by norm_cast ) <| by ring;
      simpa only [ Real.rpow_def_of_pos ( by positivity : 0 < ( md : ℝ ) ), mul_comm ] using h_exp_growth;
    -- We can factor out $k$ from the expression $((Zk X a M b r s md 0 - b * (↑r + 0 * ↑s)) : ℝ) * (md : ℝ) ^ k + b * ((r : ℝ) + (k : ℝ) * (s : ℝ))$.
    suffices h_factor : Filter.Tendsto (fun k => k * (((Zk X a M b r s md 0 - b * (↑r + 0 * ↑s)) : ℝ) * (md : ℝ) ^ k / k + b * (s : ℝ))) Filter.atTop Filter.atTop by
      rw [ Filter.tendsto_atTop_atTop ] at *;
      intro b_1; obtain ⟨ i, hi ⟩ := h_factor ( b_1 - b * r ) ; use Max.max i 1; intros a_1 ha_1; specialize hi a_1 ( le_trans ( le_max_left _ _ ) ha_1 ) ; rw [ mul_add ] at hi; rw [ mul_div_cancel₀ _ ( by linarith [ le_max_right i 1 ] ) ] at hi; linarith;
    -- We can use the fact that $((Zk X a M b r s md 0 - b * (↑r + 0 * ↑s)) : ℝ) * (md : ℝ) ^ k / k$ tends to infinity as $k$ tends to infinity.
    have h_term_inf : Filter.Tendsto (fun k => ((Zk X a M b r s md 0 - b * (↑r + 0 * ↑s)) : ℝ) * (md : ℝ) ^ k / k) Filter.atTop Filter.atTop := by
      simpa only [ mul_div_assoc ] using h_exp_growth.const_mul_atTop ( mod_cast sub_pos.mpr hZ0 );
    apply Filter.Tendsto.atTop_mul_atTop₀;
    · exact Filter.tendsto_id;
    · exact Filter.Tendsto.atTop_add h_term_inf tendsto_const_nhds;
  refine' Filter.tendsto_atTop_mono' _ _ _;
  use fun k => ⌊ ( ( Zk X a M b r s md 0 - b * ( r + 0 * s ) ) * md ^ k + b * ( r + k * s ) ) ⌋;
  · filter_upwards [ Filter.eventually_gt_atTop 0 ] with k hk using Int.le_of_lt_add_one <| Int.floor_lt.mpr <| by norm_num; have := h_W_ge_exp k; norm_num [ ← @Int.cast_le ℝ ] at *; linarith;
  · rw [ Filter.tendsto_atTop_atTop ] at *;
    intro b; rcases h_W_inf b with ⟨ i, hi ⟩ ; exact ⟨ ⌈i⌉₊, fun n hin => Int.le_floor.2 <| mod_cast hi n <| Nat.le_of_ceil_le hin ⟩ ;

lemma covering (X a L M b : ℤ) (r s : ℕ) (md : ℤ)
    (ha : 0 < a) (hmd : 2 ≤ md)
    (hLM : L ≤ M) (hM : 0 < M)
    (ineq1a : 0 ≤ b * ↑r * (md - 1) - b * ↑s + a * (M - L))
    (ineq1b : 0 ≤ b * ↑s * (md - 1) + a * (M - L))
    (hZ0 : Zk X a M b r s md 0 > b * ((r : ℤ) + 0 * (s : ℤ)))
    (n : ℤ)
    (hn : (md - 1) * X - a * (M - L) ≤ (md - 1) * n) :
    ∃ k, (md - 1) * (Yk X a L b r s md k) - a * (M - L) ≤ (md - 1) * n ∧
         (md - 1) * n ≤ (md - 1) * (Zk X a M b r s md k) + a * (M - L) := by
  have hZ_inf : Filter.Tendsto (fun k => (md - 1) * Zk X a M b r s md k + a * (M - L)) Filter.atTop Filter.atTop := by
    apply Filter.Tendsto.atTop_add _ tendsto_const_nhds
    rw [Filter.tendsto_atTop_atTop]
    intro N
    have hZt := Zk_tendsto_atTop X a M b r s md ha hmd hM hZ0
    rw [Filter.tendsto_atTop_atTop] at hZt
    obtain ⟨K, hK⟩ := hZt (max 0 N)
    refine ⟨K, fun k hk => ?_⟩
    have h := hK k hk
    have h0 : 0 ≤ Zk X a M b r s md k := by linarith [le_max_left 0 N]
    have hN : N ≤ Zk X a M b r s md k := by linarith [le_max_right 0 N]
    calc N ≤ Zk X a M b r s md k := hN
      _ = 1 * Zk X a M b r s md k := (one_mul _).symm
      _ ≤ (md - 1) * Zk X a M b r s md k := by exact mul_le_mul_of_nonneg_right (by linarith) h0
  have h_exists_k : ∃ k, (md - 1) * n ≤ (md - 1) * Zk X a M b r s md k + a * (M - L) ∧ ∀ j < k, (md - 1) * n > (md - 1) * Zk X a M b r s md j + a * (M - L) := by
    obtain ⟨ k, hk ⟩ := Filter.eventually_atTop.mp ( hZ_inf.eventually_ge_atTop ( ( md - 1 ) * n ) );
    exact ⟨ Nat.find ( ⟨ k, hk k le_rfl ⟩ : ∃ k, ( md - 1 ) * n ≤ ( md - 1 ) * Zk X a M b r s md k + a * ( M - L ) ), Nat.find_spec ( ⟨ k, hk k le_rfl ⟩ : ∃ k, ( md - 1 ) * n ≤ ( md - 1 ) * Zk X a M b r s md k + a * ( M - L ) ), fun j hj => not_le.1 fun h => Nat.find_min ( ⟨ k, hk k le_rfl ⟩ : ∃ k, ( md - 1 ) * n ≤ ( md - 1 ) * Zk X a M b r s md k + a * ( M - L ) ) hj h ⟩;
  obtain ⟨ k, hk₁, hk₂ ⟩ := h_exists_k; use k; induction' k with k ih <;> simp_all +decide ;
  · convert hn using 1;
  · have := hk₂ k le_rfl; have := Yk_succ_le_Zk X a L M b r s md hmd hLM ineq1a ineq1b k; nlinarith;

set_option maxHeartbeats 800000 in
lemma induction_lemma
    (a : ℤ) (ha : 0 < a)
    (b : ℤ)
    (d : ℕ) (hd : 0 < d)
    (m : ℕ) (hm : 2 ≤ m)
    (hcop : Int.gcd a ↑m = 1)
    (s : ℕ) (hs_div : (a : ℤ) ∣ (s : ℤ))
    (S : Set ℚ)
    (Q : Finset ℕ → Prop)
    (getβ : ℚ → Fin (m ^ d) → ℚ)
    (getA : ℚ → Fin (m ^ d) → Finset ℕ)
    (prop_pos : ∀ α ∈ S, ∀ i, ∀ x ∈ getA α i, 0 < x)
    (prop1 : ∀ α ∈ S, ∀ i, getβ α i ∈ S)
    (prop2 : ∀ α ∈ S, ∀ i : Fin (m ^ d), sumPow (getA α i) d % ((m : ℤ) ^ d) = ↑i.val)
    (prop3 : ∀ α ∈ S, ∀ i, (getA α i).card = s)
    (prop4 : ∀ α ∈ S, ∀ i, (α : ℚ) = sumRecip (getA α i) + getβ α i / (m : ℚ))
    (prop5 : ∀ α ∈ S, ∀ i, ∀ B, Q B → Disjoint (getA α i) (mFinset m B))
    (prop6 : ∀ α ∈ S, ∀ i, ∀ B, Q B → Q ((getA α i) ∪ mFinset m B))
    (L : ℤ) (hL : ∀ α ∈ S, ∀ i, L ≤ sumPow (getA α i) d)
    (M : ℤ) (hM : ∀ α ∈ S, ∀ i, sumPow (getA α i) d ≤ M)
    (r : ℕ)
    (X : ℤ)
    (base : ∀ α ∈ S, ∀ n : ℤ,
      ((m : ℤ) ^ d - 1) * X - a * (M - L) ≤ ((m : ℤ) ^ d - 1) * n →
      ((m : ℤ) ^ d - 1) * n ≤
        ((m : ℤ) ^ d - 1) * ((m : ℤ) ^ d * X + a * M) + a * (M - L) →
      a ∣ n - b * ↑r →
      ∃ A : Finset ℕ, Q A ∧ (∀ x ∈ A, 0 < x) ∧ A.card = r ∧ sumF a b d A = n ∧ sumRecip A = α)
    (k : ℕ) :
    ∀ α ∈ S, ∀ n : ℤ,
    ((m : ℤ) ^ d - 1) * (Yk X a L b r s ((m : ℤ) ^ d) k) - a * (M - L)
      ≤ ((m : ℤ) ^ d - 1) * n →
    ((m : ℤ) ^ d - 1) * n ≤
      ((m : ℤ) ^ d - 1) * (Zk X a M b r s ((m : ℤ) ^ d) k) + a * (M - L) →
    a ∣ n - b * ↑r →
    ∃ A : Finset ℕ, Q A ∧ (∀ x ∈ A, 0 < x) ∧ A.card = r + k * s ∧ sumF a b d A = n ∧ sumRecip A = α := by
  induction' k with k ih generalizing X;
  · simpa using base;
  · intro α hα n hn₁ hn₂ hn₃
    obtain ⟨i, hi⟩ : ∃ i : Fin (m ^ d), (m ^ d : ℤ) ∣ (n + Uk b r s (m ^ d) k - a * sumPow (getA α i) d) := by
      obtain ⟨ i, hi ⟩ : ∃ i : Fin (m ^ d), (m ^ d : ℤ) ∣ (n + Uk b r s (m ^ d) k - a * i.val) := by
        have h_exists_i : Int.gcd a (m ^ d) = 1 := by
          apply Int.gcd_pow_right; assumption
        generalize_proofs at *; (
        have := exists_fin_residue ( show 0 < m ^ d by positivity ) h_exists_i ( n + Uk b r s ( m ^ d ) k ) ; obtain ⟨ i, hi ⟩ := this; use i; simpa [ mul_comm ] using hi;)
      generalize_proofs at *; (
      use i; specialize prop2 α hα i; rw [ Int.dvd_iff_emod_eq_zero ] at *; simp_all +decide [ Int.add_emod, Int.sub_emod, Int.mul_emod ] ;);
    obtain ⟨ n', hn' ⟩ := hi;
    have hn'_bounds : (m ^ d - 1) * Yk X a L b r s (m ^ d) k - a * (M - L) ≤ (m ^ d - 1) * n' ∧ (m ^ d - 1) * n' ≤ (m ^ d - 1) * Zk X a M b r s (m ^ d) k + a * (M - L) := by
      constructor;
      · have hn'_lower : (m ^ d - 1) * Yk X a L b r s (m ^ d) (k + 1) - a * (M - L) ≤ (m ^ d - 1) * (m ^ d * n' + a * sumPow (getA α i) d - Uk b r s (m ^ d) k) := by
          rw [ ← hn' ] ; linarith;
        rw [ show Yk X a L b r s ( m ^ d ) ( k + 1 ) = m ^ d * Yk X a L b r s ( m ^ d ) k + a * L - Uk b r s ( m ^ d ) k from rfl ] at hn'_lower;
        nlinarith [ pow_le_pow_right₀ ( by linarith : 1 ≤ ( m : ℤ ) ) hd, hL α hα i, hM α hα i, mul_le_mul_of_nonneg_left ( hL α hα i ) ( show 0 ≤ ( m : ℤ ) ^ d - 1 by exact sub_nonneg_of_le ( one_le_pow₀ ( by linarith ) ) ), mul_le_mul_of_nonneg_left ( hM α hα i ) ( show 0 ≤ ( m : ℤ ) ^ d - 1 by exact sub_nonneg_of_le ( one_le_pow₀ ( by linarith ) ) ) ];
      · have h_sub : (m ^ d - 1) * (m ^ d * n' - Uk b r s (m ^ d) k + a * sumPow (getA α i) d) ≤ (m ^ d - 1) * Zk X a M b r s (m ^ d) (k + 1) + a * (M - L) := by
          convert hn₂ using 1 ; rw [ ← hn' ] ; ring;
        have h_sub_Zk : (m ^ d - 1) * (m ^ d * n' - Uk b r s (m ^ d) k + a * sumPow (getA α i) d) ≤ (m ^ d - 1) * (m ^ d * Zk X a M b r s (m ^ d) k + a * M - Uk b r s (m ^ d) k) + a * (M - L) := by
          convert h_sub using 1;
        nlinarith [ pow_le_pow_right₀ ( by linarith : 1 ≤ ( m : ℤ ) ) hd, hL α hα i, hM α hα i, mul_le_mul_of_nonneg_left ( hL α hα i ) ( show 0 ≤ ( m : ℤ ) ^ d - 1 by exact sub_nonneg_of_le ( one_le_pow₀ ( by linarith ) ) ), mul_le_mul_of_nonneg_left ( hM α hα i ) ( show 0 ≤ ( m : ℤ ) ^ d - 1 by exact sub_nonneg_of_le ( one_le_pow₀ ( by linarith ) ) ) ];
    have hn'_div : a ∣ n' - b * r := by
      have hn'_div : a ∣ (n - a * sumPow (getA α i) d + Uk b r s (m ^ d) k - b * r * m ^ d) := by
        obtain ⟨ k, hk ⟩ := hn₃;
        simp +decide [ show n = a * k + b * r by linarith, Uk ] ; ring_nf at * ; norm_num at * ;
        exact ⟨ k - sumPow ( getA α i ) d + b * ‹ℕ› * ( m ^ d - 1 ) * s / a - b * s / a, by linarith [ Int.ediv_mul_cancel ( show a ∣ b * ‹ℕ› * ( m ^ d - 1 ) * s from dvd_mul_of_dvd_right hs_div _ ), Int.ediv_mul_cancel ( show a ∣ b * s from dvd_mul_of_dvd_right hs_div _ ) ] ⟩;
      have hn'_div : a ∣ (m ^ d * n' - b * r * m ^ d) := by
        convert hn'_div using 1 ; rw [ ← hn' ] ; ring;
      have hn'_div : a ∣ (m ^ d * (n' - b * r)) := by
        convert hn'_div using 1 ; ring;
      refine' Int.dvd_of_dvd_mul_right_of_gcd_one hn'_div _;
      exact Int.gcd_pow_right hcop d;
    obtain ⟨B, hBQ, hBpos, hBcard, hBsumF, hBrecip⟩ : ∃ B : Finset ℕ, Q B ∧ (∀ x ∈ B, 0 < x) ∧ B.card = r + k * s ∧ sumF a b d B = n' ∧ sumRecip B = getβ α i := by
      exact ih X base ( getβ α i ) ( prop1 α hα i ) n' hn'_bounds.1 hn'_bounds.2 hn'_div;
    use getA α i ∪ mFinset m B;
    refine' ⟨ prop6 α hα i B hBQ, _, _, _, _ ⟩;
    · exact fun x hx => by simp only [Finset.mem_union] at hx; exact hx.elim (prop_pos α hα i x) (mFinset_pos (by linarith) hBpos x)
    · rw [ Finset.card_union_of_disjoint ( prop5 α hα i B hBQ ), prop3 α hα i, card_mFinset ( by linarith ) B, hBcard ] ; ring;
    · rw [ sumF_union ] <;> norm_num [ prop5 α hα i B hBQ ];
      rw [ sumF_mFinset ] <;> norm_num [ hBcard, hBsumF ];
      · unfold sumF; norm_num [ prop3 α hα i ] ; linarith! [ show Uk b r s ( m ^ d ) k = b * ( r + k * s ) * ( m ^ d - 1 ) - b * s from rfl ] ;
      · linarith;
    · rw [ sumRecip_union ];
      · rw [ sumRecip_mFinset ( by positivity ), hBrecip ];
        rw [ ← prop4 α hα i ];
      · exact prop5 α hα i B hBQ

/-- If the expression (b+j)r(md-1) - (b+j)s + a(M-L) is non-negative at j=l₁ and j=l₂,
    then it is non-negative for all j between l₁ and l₂. -/
lemma eq1a_widening (a L M : ℤ) (r s : ℕ) (md : ℤ)
    (l₁ l₂ : ℤ)
    (b : ℤ)
    (h1 : 0 ≤ (b + l₁) * ↑r * (md - 1) - (b + l₁) * ↑s + a * (M - L))
    (h2 : 0 ≤ (b + l₂) * ↑r * (md - 1) - (b + l₂) * ↑s + a * (M - L))
    (j : ℤ) (hj1 : l₁ ≤ j) (hj2 : j ≤ l₂) :
    0 ≤ (b + j) * ↑r * (md - 1) - (b + j) * ↑s + a * (M - L) := by
  by_cases h_case : (md - 1) * r - s ≥ 0;
  · nlinarith [ mul_le_mul_of_nonneg_left hj1 h_case, mul_le_mul_of_nonneg_left hj2 h_case ];
  · nlinarith

/-- If bs(m^d-1) + a(M-L) ≥ 0, then b's(m^d-1) + a(M-L) ≥ 0 for all b' ≥ b, since s*(m^d-1) ≥ 0. -/
lemma eq1b_widening (a L M : ℤ) (s : ℕ) (md : ℤ)
    (hmd : 1 ≤ md)
    (b b' : ℤ) (hbb : b ≤ b')
    (h : 0 ≤ b * ↑s * (md - 1) + a * (M - L)) :
    0 ≤ b' * ↑s * (md - 1) + a * (M - L) := by
  nlinarith [ mul_nonneg ( Nat.cast_nonneg s ) ( sub_nonneg.mpr hmd ) ]

/-- Key identity: shifting b by j shifts sumF by j * card -/
lemma sumF_add_shift (a b j : ℤ) (d : ℕ) (A : Finset ℕ) :
    sumF a (b + j) d A = sumF a b d A + j * (A.card : ℤ) := by
  unfold sumF; ring;

lemma residue_class_coverage
    (a : ℤ) (ha : 0 < a) (b j : ℤ)
    (r_w : Fin a.natAbs → ℕ)
    (hr_w : ∀ w : Fin a.natAbs, a ∣ (b * ↑(r_w w) - ↑w.val))
    (hcop_j : Int.gcd (b + j) a = 1)
    (n : ℤ) :
    ∃ w : Fin a.natAbs, a ∣ n - (b + j) * ↑(r_w w) := by
  have h_set : Finset.image (fun w => ((b + j) * r_w w) % a) (Finset.univ : Finset (Fin a.natAbs)) = Finset.image (fun k => k) (Finset.Ico 0 a) := by
    refine' Finset.eq_of_subset_of_card_le ( _ ) _;
    · exact Finset.image_subset_iff.mpr fun w _ => Finset.mem_image.mpr ⟨ ( b + j ) * r_w w % a, Finset.mem_Ico.mpr ⟨ Int.emod_nonneg _ ha.ne', Int.emod_lt_of_pos _ ha ⟩, rfl ⟩;
    · rw [ Finset.card_image_of_injective _ fun x y hxy => by aesop, Finset.card_image_of_injOn ];
      · simp +decide [ Finset.card_univ, abs_of_pos ha ];
      · intros w hw w' hw' h; simp_all +decide [ Int.emod_eq_emod_iff_emod_sub_eq_zero ] ;
        have h_div : a ∣ (r_w w - r_w w') := by
          exact Int.dvd_of_dvd_mul_right_of_gcd_one ( by convert h using 1; ring ) ( Int.gcd_comm _ _ ▸ hcop_j );
        have h_eq : a ∣ (w - w') := by
          convert dvd_sub ( hr_w w' ) ( hr_w w |> Int.dvd_sub <| h_div.mul_left b ) using 1 ; ring;
        exact Fin.ext ( by obtain ⟨ k, hk ⟩ := h_eq; nlinarith [ show k = 0 by nlinarith [ Fin.is_lt w, Fin.is_lt w', abs_of_pos ha ] ] );
  simp +decide [ Finset.ext_iff ] at h_set;
  exact Exists.elim ( h_set ( n % a ) |>.2 ⟨ Int.emod_nonneg _ ha.ne', Int.emod_lt_of_pos _ ha ⟩ ) fun w hw => ⟨ w, Int.dvd_of_emod_eq_zero ( by simp [ Int.sub_emod, hw ] ) ⟩

lemma base_case_shift
    (a : ℤ) (b j : ℤ) (d : ℕ) (m : ℕ)
    (S : Set ℚ) (Q : Finset ℕ → Prop)
    (L M : ℤ)
    (l₁ l₂ : ℤ) (hl₁ : l₁ ≤ 0) (hl₂ : 0 ≤ l₂)
    (_hj1 : l₁ ≤ j) (hj2 : j ≤ l₂)
    (hmd : 2 ≤ (m : ℤ) ^ d)
    (X_w : ℤ) (r_w : ℕ)
    (base_f : ∀ α ∈ S, ∀ n : ℤ,
      ((m : ℤ) ^ d - 1) * (X_w + l₁ * ↑r_w) - a * (M - L) ≤ ((m : ℤ) ^ d - 1) * n →
      ((m : ℤ) ^ d - 1) * n ≤
        ((m : ℤ) ^ d - 1) * ((m : ℤ) ^ d * (X_w + l₂ * ↑r_w) + a * M) + a * (M - L) →
      a ∣ n - b * ↑r_w →
      ∃ A : Finset ℕ, Q A ∧ (∀ x ∈ A, 0 < x) ∧ A.card = r_w ∧ sumF a b d A = n ∧ sumRecip A = α)
    : ∀ α ∈ S, ∀ n : ℤ,
      ((m : ℤ) ^ d - 1) * (X_w + j * ↑r_w) - a * (M - L) ≤ ((m : ℤ) ^ d - 1) * n →
      ((m : ℤ) ^ d - 1) * n ≤
        ((m : ℤ) ^ d - 1) * ((m : ℤ) ^ d * (X_w + j * ↑r_w) + a * M) + a * (M - L) →
      a ∣ n - (b + j) * ↑r_w →
      ∃ A : Finset ℕ, Q A ∧ (∀ x ∈ A, 0 < x) ∧ A.card = r_w ∧ sumF a (b + j) d A = n ∧ sumRecip A = α := by
  intro α hα n hn_lower hn_upper hn_div
  set n' := n - j * ↑r_w with hn'_def
  have hn'_div : a ∣ n' - b * ↑r_w := by
    convert hn_div using 1; ring
  have hn'_lower : ((m : ℤ) ^ d - 1) * (X_w + l₁ * ↑r_w) - a * (M - L) ≤
      ((m : ℤ) ^ d - 1) * n' := by
    have hr_nn : (0 : ℤ) ≤ (r_w : ℤ) := Nat.cast_nonneg r_w
    have h_l1r_nonpos : l₁ * (r_w : ℤ) ≤ 0 := mul_nonpos_of_nonpos_of_nonneg hl₁ hr_nn
    have h_md1 : (0 : ℤ) < (m : ℤ) ^ d - 1 := by linarith
    have h1 : ((m : ℤ) ^ d - 1) * (l₁ * (r_w : ℤ)) ≤ 0 :=
      mul_nonpos_of_nonneg_of_nonpos (le_of_lt h_md1) h_l1r_nonpos
    nlinarith
  have hn'_upper : ((m : ℤ) ^ d - 1) * n' ≤
      ((m : ℤ) ^ d - 1) * ((m : ℤ) ^ d * (X_w + l₂ * ↑r_w) + a * M) + a * (M - L) := by
    have hr_nn : (0 : ℤ) ≤ (r_w : ℤ) := Nat.cast_nonneg r_w
    have hj_le_l2 : ((m : ℤ) ^ d - 1) * j ≤ ((m : ℤ) ^ d - 1) * l₂ :=
      mul_le_mul_of_nonneg_left hj2 (by linarith)
    have h_md1_le : ((m : ℤ) ^ d - 1) * l₂ ≤ (m : ℤ) ^ d * l₂ :=
      mul_le_mul_of_nonneg_right (by linarith : ((m : ℤ) ^ d - 1) ≤ (m : ℤ) ^ d) hl₂
    have h_key : ((m : ℤ) ^ d - 1) * j * (r_w : ℤ) ≤ (m : ℤ) ^ d * l₂ * (r_w : ℤ) := by
      have : ((m : ℤ) ^ d - 1) * j ≤ (m : ℤ) ^ d * l₂ := le_trans hj_le_l2 h_md1_le
      exact mul_le_mul_of_nonneg_right this hr_nn
    nlinarith
  obtain ⟨A, hQ, hApos, hcard, hsumF, hrecip⟩ := base_f α hα n' hn'_lower hn'_upper hn'_div
  refine ⟨A, hQ, hApos, hcard, ?_, hrecip⟩
  have := sumF_add_shift a b j d A
  rw [hcard] at this
  linarith

lemma lower_T_iff (a L M P n : ℤ) (m : ℕ) (d : ℕ) (hmd : 1 < (m : ℤ) ^ d) :
    ((P : ℚ) - baseTolerance a L M m d ≤ (n : ℚ)) ↔
    (((m : ℤ) ^ d - 1) * P - a * (M - L) ≤ ((m : ℤ) ^ d - 1) * n) := by
  rw [ sub_le_iff_le_add ];
  rw [ show baseTolerance a L M m d = ( a * ( M - L ) : ℚ ) / ( m ^ d - 1 ) by rfl, add_div', le_div_iff₀ ] <;> norm_cast at *;
  · grind +ring;
  · rw [ Int.subNatNat_eq_coe ] ; norm_num ; linarith;
  · rw [ Int.subNatNat_eq_coe ] ; norm_num ; linarith

lemma upper_T_iff (a L M Q n : ℤ) (m : ℕ) (d : ℕ) (hmd : 1 < (m : ℤ) ^ d) :
    ((n : ℚ) ≤ (m : ℚ) ^ d * (Q : ℚ) + (a : ℚ) * (M : ℚ) + baseTolerance a L M m d) ↔
    (((m : ℤ) ^ d - 1) * n ≤ ((m : ℤ) ^ d - 1) * ((m : ℤ) ^ d * Q + a * M) + a * (M - L)) := by
  unfold baseTolerance;
  rw [ add_div', le_div_iff₀ ] <;> norm_cast at *;
  · ring_nf;
  · grind;
  · rw [ Int.subNatNat_eq_coe ] ; norm_num ; linarith

/-- Convert a base case from T (rational) form to the multiplied-out ℤ form. -/
lemma base_from_T_form {a L M : ℤ} {m : ℕ} {d : ℕ} (hmd : 1 < (m : ℤ) ^ d)
    {S : Set ℚ} {Q : Finset ℕ → Prop} {b : ℤ} {P₁ P₂ : ℤ} {r : ℕ}
    (base : ∀ α ∈ S, ∀ n : ℤ,
      (P₁ : ℚ) - baseTolerance a L M m d ≤ (n : ℚ) →
      (n : ℚ) ≤ (m : ℚ) ^ d * (P₂ : ℚ) + (a : ℚ) * (M : ℚ) + baseTolerance a L M m d →
      a ∣ n - b * ↑r →
      ∃ A : Finset ℕ, Q A ∧ (∀ x ∈ A, 0 < x) ∧ A.card = r ∧ sumF a b d A = n ∧ sumRecip A = α)
    : ∀ α ∈ S, ∀ n : ℤ,
      ((m : ℤ) ^ d - 1) * P₁ - a * (M - L) ≤ ((m : ℤ) ^ d - 1) * n →
      ((m : ℤ) ^ d - 1) * n ≤
        ((m : ℤ) ^ d - 1) * ((m : ℤ) ^ d * P₂ + a * M) + a * (M - L) →
      a ∣ n - b * ↑r →
      ∃ A : Finset ℕ, Q A ∧ (∀ x ∈ A, 0 < x) ∧ A.card = r ∧ sumF a b d A = n ∧ sumRecip A = α := by
  intro α hα n hn_l hn_u hn_d
  exact base α hα n
    ((lower_T_iff a L M P₁ n m d hmd).mpr hn_l)
    ((upper_T_iff a L M P₂ n m d hmd).mpr hn_u) hn_d

/-- Convert a base case from the multiplied-out ℤ form to T (rational) form. -/
lemma base_to_T_form {a L M : ℤ} {m : ℕ} {d : ℕ} (hmd : 1 < (m : ℤ) ^ d)
    {S : Set ℚ} {Q : Finset ℕ → Prop} {b : ℤ} {P : ℤ} {r : ℕ}
    (base : ∀ α ∈ S, ∀ n : ℤ,
      ((m : ℤ) ^ d - 1) * P - a * (M - L) ≤ ((m : ℤ) ^ d - 1) * n →
      ((m : ℤ) ^ d - 1) * n ≤
        ((m : ℤ) ^ d - 1) * ((m : ℤ) ^ d * P + a * M) + a * (M - L) →
      a ∣ n - b * ↑r →
      ∃ A : Finset ℕ, Q A ∧ (∀ x ∈ A, 0 < x) ∧ A.card = r ∧ sumF a b d A = n ∧ sumRecip A = α)
    : ∀ α ∈ S, ∀ n : ℤ,
      (P : ℚ) - baseTolerance a L M m d ≤ (n : ℚ) →
      (n : ℚ) ≤ (m : ℚ) ^ d * (P : ℚ) + (a : ℚ) * (M : ℚ) + baseTolerance a L M m d →
      a ∣ n - b * ↑r →
      ∃ A : Finset ℕ, Q A ∧ (∀ x ∈ A, 0 < x) ∧ A.card = r ∧ sumF a b d A = n ∧ sumRecip A = α := by
  intro α hα n hn_l hn_u hn_d
  exact base α hα n
    ((lower_T_iff a L M P n m d hmd).mp hn_l)
    ((upper_T_iff a L M P n m d hmd).mp hn_u) hn_d

/-- First metatheorem. -/
theorem meta_theorem
    (a : ℤ) (ha : 0 < a)
    (b : ℤ)
    (d : ℕ) (hd : 0 < d)
    (m : ℕ) (hm : 2 ≤ m)
    (hcop : Int.gcd a ↑m = 1)
    (s : ℕ) (hs_div : (a : ℤ) ∣ (s : ℤ))
    (S : Set ℚ)
    (Q : Finset ℕ → Prop)
    (getβ : ℚ → Fin (m ^ d) → ℚ)
    (getA : ℚ → Fin (m ^ d) → Finset ℕ)
    (prop_pos : ∀ α ∈ S, ∀ i, ∀ x ∈ getA α i, 0 < x)
    (prop1 : ∀ α ∈ S, ∀ i, getβ α i ∈ S)
    (prop2 : ∀ α ∈ S, ∀ i : Fin (m ^ d), sumPow (getA α i) d % ((m : ℤ) ^ d) = ↑i.val)
    (prop3 : ∀ α ∈ S, ∀ i, (getA α i).card = s)
    (prop4 : ∀ α ∈ S, ∀ i, (α : ℚ) = sumRecip (getA α i) + getβ α i / (m : ℚ))
    (prop5 : ∀ α ∈ S, ∀ i, ∀ B, Q B → Disjoint (getA α i) (mFinset m B))
    (prop6 : ∀ α ∈ S, ∀ i, ∀ B, Q B → Q ((getA α i) ∪ mFinset m B))
    (L : ℤ) (hL : ∀ α ∈ S, ∀ i, L ≤ sumPow (getA α i) d)
    (M : ℤ) (hM : ∀ α ∈ S, ∀ i, sumPow (getA α i) d ≤ M)
    (r : ℕ)
    (X : ℤ) (hX : 0 ≤ X)
    (ineq1a : 0 ≤ b * ↑r * ((m : ℤ) ^ d - 1) - b * ↑s + a * (M - L))
    (ineq1b : 0 ≤ b * ↑s * ((m : ℤ) ^ d - 1) + a * (M - L))
    (base : ∀ α ∈ S, ∀ n : ℤ,
      (X : ℚ) - baseTolerance a L M m d ≤ (n : ℚ) →
      (n : ℚ) ≤ (m : ℚ) ^ d * (X : ℚ) + (a : ℚ) * (M : ℚ) + baseTolerance a L M m d →
      a ∣ n - b * ↑r →
      ∃ A : Finset ℕ, Q A ∧ (∀ x ∈ A, 0 < x) ∧ A.card = r ∧ sumF a b d A = n ∧ sumRecip A = α)
    : ∀ α ∈ S, ∀ n : ℤ,
      ((m : ℤ) ^ d - 1) * X - a * (M - L) ≤ ((m : ℤ) ^ d - 1) * n →
      a ∣ n - b * ↑r →
      ∃ A : Finset ℕ, Q A ∧ (∀ x ∈ A, 0 < x) ∧ sumF a b d A = n ∧ sumRecip A = α := by
  intro α hα n hn hn_div
  have hmd_gt1 : 1 < (m : ℤ) ^ d := by
    have : 2 ≤ m ^ d := le_trans hm (Nat.le_self_pow hd.ne' m); linarith
  have base_old := base_from_T_form hmd_gt1 base
  have hmc_ge : (2 : ℤ) ≤ (m : ℤ) ^ d := by
    have : 2 ≤ m ^ d := le_trans hm (Nat.le_self_pow hd.ne' m)
    exact_mod_cast this
  have hLM : L ≤ M := by
      let i0 : Fin (m ^ d) := ⟨0, by positivity⟩
      specialize hL α hα i0; specialize hM α hα i0; linarith
  have hM_pos : (0 : ℤ) < M := by
      have h1lt : 1 < m ^ d := by linarith [Nat.le_self_pow hd.ne' m]
      let i1 : Fin (m ^ d) := ⟨1, h1lt⟩
      have h_sp := hM α hα i1
      have h_mod := prop2 α hα i1
      have h_sp_nn := sumPow_nonneg (getA α i1) d
      have h_sp_pos : 1 ≤ sumPow (getA α i1) d := by
        have h3 := Int.mul_ediv_add_emod (sumPow (getA α i1) d) ((m : ℤ) ^ d)
        have h4 : 0 ≤ sumPow (getA α i1) d / ((m : ℤ) ^ d) :=
          Int.ediv_nonneg h_sp_nn (by positivity)
        simp only [i1, Nat.cast_one] at h_mod
        rw [h_mod] at h3
        nlinarith
      linarith
  have hM1 : (1 : ℤ) ≤ M := by linarith
  have hZ0 : (m : ℤ) ^ d * X + a * M > b * ↑r := by
    obtain ⟨n₀, hn₀_div, hn₀_lower, hn₀_upper⟩ := interval_has_residue X a (b * ↑r) ha
    obtain ⟨hrange_l, hrange_u⟩ := interval_in_base_range X a M L ((m : ℤ) ^ d)
      hmc_ge hX ha hLM hM1 n₀ hn₀_lower hn₀_upper
    obtain ⟨A, _, _, hcard, hsumF, _⟩ := base_old α hα n₀ hrange_l hrange_u hn₀_div
    have h_sp := sumPow_nonneg A d
    have h_n0_ge_br : b * ↑r ≤ n₀ := by
      have := sumPow_nonneg A d
      unfold sumF at hsumF; rw [hcard] at hsumF; nlinarith
    have h_z0_ge := z0_ge_x_plus_a X a M ((m : ℤ) ^ d) hmc_ge hX ha hM1
    linarith
  obtain ⟨k, hk⟩ : ∃ k, ((m ^ d - 1) * (Yk X a L b r s (m ^ d) k) - a * (M - L) ≤
                            (m ^ d - 1) * n ∧
                            (m ^ d - 1) * n ≤ (m ^ d - 1) * (Zk X a M b r s (m ^ d) k) + a * (M - L)) := by
    refine covering X a L M b r s ((m : ℤ) ^ d) ha ?_ hLM ?_ ineq1a ineq1b ?_ n hn
    · exact_mod_cast hmc_ge
    · linarith
    · simpa [Zk] using hZ0
  obtain ⟨A, hA⟩ : ∃ A : Finset ℕ, Q A ∧ (∀ x ∈ A, 0 < x) ∧ A.card = r + k * s ∧ sumF a b d A = n ∧ sumRecip A = α := by
    apply induction_lemma a ha b d hd m hm hcop s hs_div S Q getβ getA prop_pos prop1 prop2 prop3 prop4 prop5 prop6 L hL M hM r X base_old k α hα n hk.left hk.right hn_div
  use A
  exact ⟨hA.1, hA.2.1, hA.2.2.2.1, hA.2.2.2.2⟩

set_option maxHeartbeats 800000 in
/-- Second metatheorem. -/
theorem general_theorem
    (a : ℤ) (ha : 0 < a)
    (b : ℤ)
    (d : ℕ) (hd : 0 < d)
    (m : ℕ) (hm : 2 ≤ m)
    (hcop : Int.gcd a ↑m = 1)
    (s : ℕ) (hs_div : (a : ℤ) ∣ (s : ℤ))
    (S : Set ℚ)
    (Q : Finset ℕ → Prop)
    (getβ : ℚ → Fin (m ^ d) → ℚ)
    (getA : ℚ → Fin (m ^ d) → Finset ℕ)
    (prop_pos : ∀ α ∈ S, ∀ i, ∀ x ∈ getA α i, 0 < x)
    (prop1 : ∀ α ∈ S, ∀ i, getβ α i ∈ S)
    (prop2 : ∀ α ∈ S, ∀ i : Fin (m ^ d), sumPow (getA α i) d % ((m : ℤ) ^ d) = ↑i.val)
    (prop3 : ∀ α ∈ S, ∀ i, (getA α i).card = s)
    (prop4 : ∀ α ∈ S, ∀ i, (α : ℚ) = sumRecip (getA α i) + getβ α i / (m : ℚ))
    (prop5 : ∀ α ∈ S, ∀ i, ∀ B, Q B → Disjoint (getA α i) (mFinset m B))
    (prop6 : ∀ α ∈ S, ∀ i, ∀ B, Q B → Q ((getA α i) ∪ mFinset m B))
    (L : ℤ) (hL : ∀ α ∈ S, ∀ i, L ≤ sumPow (getA α i) d)
    (M : ℤ) (hM : ∀ α ∈ S, ∀ i, sumPow (getA α i) d ≤ M)
    (l₁ l₂ : ℤ) (hl₁ : l₁ ≤ 0) (hl₂ : 0 ≤ l₂)
    (r_w : Fin a.natAbs → ℕ) (hr_w : ∀ w : Fin a.natAbs, a ∣ (b * ↑(r_w w) - ↑w.val))
    (X_w : Fin a.natAbs → ℤ) (hX_lower : ∀ w : Fin a.natAbs, 0 ≤ X_w w + l₁ * ↑(r_w w))
    (ineq2a : ∀ w : Fin a.natAbs, 0 ≤ (b + l₁) * ↑(r_w w) * ((m : ℤ) ^ d - 1) - (b + l₁) * ↑s + a * (M - L))
    (ineq2b : ∀ w : Fin a.natAbs, 0 ≤ (b + l₂) * ↑(r_w w) * ((m : ℤ) ^ d - 1) - (b + l₂) * ↑s + a * (M - L))
    (ineq2c : 0 ≤ (b + l₁) * ↑s * ((m : ℤ) ^ d - 1) + a * (M - L))
    (base_general : ∀ w : Fin a.natAbs, ∀ α ∈ S, ∀ n : ℤ,
      (X_w w + l₁ * ↑(r_w w) : ℤ) - baseTolerance a L M m d ≤ (n : ℚ) →
      (n : ℚ) ≤ (m : ℚ) ^ d * (X_w w + l₂ * ↑(r_w w) : ℤ) + (a : ℚ) * (M : ℚ) + baseTolerance a L M m d →
      a ∣ n - b * ↑(r_w w) →
      ∃ A : Finset ℕ, Q A ∧ (∀ x ∈ A, 0 < x) ∧ A.card = r_w w ∧ sumF a b d A = n ∧ sumRecip A = α)
    : ∀ j : ℤ, l₁ ≤ j → j ≤ l₂ → Int.gcd (b + j) a = 1 →
      ∀ α ∈ S,
        n₀ (fun x : ℕ => a * (x : ℤ) ^ d + (b + j)) α ≤
          ↑(Finset.univ.sup' ⟨⟨0, Int.natAbs_pos.mpr ha.ne'⟩, Finset.mem_univ _⟩
            (fun w : Fin a.natAbs => X_w w + j * ↑(r_w w) - a * (M - L) / ((m : ℤ) ^ d - 1))) := by
  intro j hj1 hj2 hcop_j α hα
  have hmd_gt1 : 1 < (m : ℤ) ^ d := by
    have : 2 ≤ m ^ d := le_trans hm (Nat.le_self_pow hd.ne' m); linarith
  have base_general_old : ∀ w : Fin a.natAbs, ∀ α ∈ S, ∀ n : ℤ,
      ((m : ℤ) ^ d - 1) * (X_w w + l₁ * ↑(r_w w)) - a * (M - L) ≤ ((m : ℤ) ^ d - 1) * n →
      ((m : ℤ) ^ d - 1) * n ≤
        ((m : ℤ) ^ d - 1) * ((m : ℤ) ^ d * (X_w w + l₂ * ↑(r_w w)) + a * M) + a * (M - L) →
      a ∣ n - b * ↑(r_w w) →
      ∃ A : Finset ℕ, Q A ∧ (∀ x ∈ A, 0 < x) ∧ A.card = r_w w ∧ sumF a b d A = n ∧ sumRecip A = α :=
    fun w => base_from_T_form hmd_gt1 (base_general w)
  set T := a * (M - L) / ((m : ℤ) ^ d - 1) with hT_def
  set hne_wit : (Finset.univ : Finset (Fin a.natAbs)).Nonempty :=
    ⟨⟨0, Int.natAbs_pos.mpr ha.ne'⟩, Finset.mem_univ _⟩
  set bound := Finset.univ.sup' hne_wit
    (fun w : Fin a.natAbs => X_w w + j * ↑(r_w w) - T) with hbound_def
  apply n₀_le _ α bound
  · intro n hn_bound
    have hmd_ge : (2 : ℤ) ≤ (m : ℤ) ^ d := by
      have : 2 ≤ m ^ d := le_trans hm (Nat.le_self_pow hd.ne' m)
      exact_mod_cast this
    have hmd_pos : (0 : ℤ) < (m : ℤ) ^ d - 1 := by linarith
    have hLM : L ≤ M := by
      let i0 : Fin (m ^ d) := ⟨0, by positivity⟩
      specialize hL α hα i0; specialize hM α hα i0; linarith
    have hT_mul : ((m : ℤ) ^ d - 1) * T ≤ a * (M - L) := by
      have := Int.mul_ediv_add_emod (a * (M - L)) ((m : ℤ) ^ d - 1)
      have := Int.emod_nonneg (a * (M - L)) hmd_pos.ne'
      linarith
    have hn : ∀ w : Fin a.natAbs,
        ((m : ℤ) ^ d - 1) * n ≥
          ((m : ℤ) ^ d - 1) * (X_w w + j * ↑(r_w w)) - a * (M - L) := by
      intro w
      have h_le : X_w w + j * ↑(r_w w) - T ≤ bound :=
        Finset.le_sup' (fun w : Fin a.natAbs => X_w w + j * ↑(r_w w) - T) (Finset.mem_univ w)
      have h1 : X_w w + j * ↑(r_w w) - T ≤ n := le_trans h_le hn_bound
      have h2 : ((m : ℤ) ^ d - 1) * (X_w w + j * ↑(r_w w) - T) ≤ ((m : ℤ) ^ d - 1) * n :=
        Int.mul_le_mul_of_nonneg_left h1 (le_of_lt hmd_pos)
      linarith [show ((m : ℤ) ^ d - 1) * (X_w w + j * ↑(r_w w) - T) =
        ((m : ℤ) ^ d - 1) * (X_w w + j * ↑(r_w w)) - ((m : ℤ) ^ d - 1) * T from by ring]
    obtain ⟨w₀, hw₀⟩ := residue_class_coverage a ha b j r_w hr_w hcop_j n
    have hX_nonneg : 0 ≤ X_w w₀ + j * ↑(r_w w₀) := by
      have h1 := hX_lower w₀
      have hr_nn : 0 ≤ (r_w w₀ : ℤ) := Nat.cast_nonneg (r_w w₀)
      have h_diff_nonneg : 0 ≤ (j - l₁) * ↑(r_w w₀) :=
        mul_nonneg (by linarith) hr_nn
      linarith [show X_w w₀ + j * ↑(r_w w₀) = (X_w w₀ + l₁ * ↑(r_w w₀)) + (j - l₁) * ↑(r_w w₀) by ring]
    have hM_pos : (0 : ℤ) < M := by
      have h1lt : 1 < m ^ d := by linarith [Nat.le_self_pow hd.ne' m]
      let i1 : Fin (m ^ d) := ⟨1, h1lt⟩
      have h_sp := hM α hα i1
      have h_mod := prop2 α hα i1
      have h_sp_nn := sumPow_nonneg (getA α i1) d
      have h_sp_pos : 1 ≤ sumPow (getA α i1) d := by
        have h3 := Int.mul_ediv_add_emod (sumPow (getA α i1) d) ((m : ℤ) ^ d)
        have h4 : 0 ≤ sumPow (getA α i1) d / ((m : ℤ) ^ d) :=
          Int.ediv_nonneg h_sp_nn (by positivity)
        simp only [i1, Nat.cast_one] at h_mod
        rw [h_mod] at h3
        nlinarith
      linarith
    have base_shifted := base_to_T_form hmd_gt1
      (base_case_shift a b j d m S Q L M l₁ l₂ hl₁ hl₂ hj1 hj2 hmd_ge
        (X_w w₀) (r_w w₀) (base_general_old w₀))
    have h_result := meta_theorem a ha (b + j) d hd m hm hcop s hs_div S Q getβ getA prop_pos
      prop1 prop2 prop3 prop4 prop5 prop6 L hL M hM
      (r_w w₀) (X_w w₀ + j * ↑(r_w w₀))
      hX_nonneg
      (eq1a_widening a L M (r_w w₀) s ((m : ℤ) ^ d) l₁ l₂ b (ineq2a w₀) (ineq2b w₀) j hj1 hj2)
      (eq1b_widening a L M s ((m : ℤ) ^ d) (by linarith) (b + l₁) (b + j) (by linarith) ineq2c)
      base_shifted
      α hα n (by linarith [hn w₀]) hw₀
    obtain ⟨A, _, hApos, hsumF, hrecip⟩ := h_result
    exact ⟨A, hApos, by rw [← sumF_eq_sum]; exact hsumF, hrecip⟩
  · exact bdd_below_poly_threshold a ha (b + j) d hd α

#print axioms meta_theorem
#print axioms general_theorem
