/-
Solving Erdős problem 1136 (https://www.erdosproblems.com/1136), Helmut Müller
proved that the set A of positive integers whose odd part is congruent to 3 (mod
4) has the property that no two elements (possibly equal) sum to a power of two,
   and that A has natural density 1/2. He also showed that any set of positive
   integers with this sum-free property has density ≤ 1/2.

Müller, Helmut, Über ein additiv-zahlentheoretisches Problem von P. Erdős. Mitt.
Math. Ges. Hamburg (2011), 75--78.

Below you can find a formalization of the result, which was generated by
Aristotle from Harmonic (https://aristotle.harmonic.fun).

A similar formalization was already obtained by Lorenzo Luccioli and can be
verified here:

https://live.lean-lang.org/#project=mathlib-v4.28.0&url=https%3A%2F%2Fgist.githubusercontent.com%2FLorenzoLuccioli%2F08616fb4e219e0dbba282bedabcf524b%2Fraw%2Fa2051b19d529d149e10ad670f70864f5671e823f%2FErdos1136.lean

The formalization below also contains the following more general upper bound
result:

Let S = {s_1 < s_2 < ⋯ } ⊆ ℕ be any infinite set of positive integers for which

s_{k+1} ≤ 2s_k + 2

holds for all k. Then for any positive integer n and any set A ⊆ ℕ satisfying

|A| > (n + s_1)/2

we have (A+A) ∩ S ≠ ∅. In particular, if A has upper density larger than 1/2,
then A+A contains infinitely many elements of S.

Finally, we also provide another construction of a power-of-two sum-free set
with natural density 1/2, namely the greedy construction! Simply let a_k be the
smallest positive integer such that a_j + a_k is not a power of two for all 1 ≤
j ≤ k, and let A = {a_k : k ≥ 1}. Surprisingly, this works as well. And by the
way, instead of the powers of two, this greedy construction also works for every
sequence s_1, s_2, … with s_k ≥ 2s_{k-1} for all k.

Lean version: leanprover/lean4:v4.28.0 Mathlib version:
8f9d9cff6bd728b17a24e163c9402775d9e6a365
-/

import Mathlib

set_option maxHeartbeats 800000

open Finset Nat

/-!
# Sum-free sets avoiding power-of-2 sums

We prove that:
1. The set A of positive integers whose odd part is ≡ 3 (mod 4) has the property that
   no two elements (possibly equal) sum to a power of 2.
2. A has natural density 1/2 (proved using an injection argument showing the complement
   of A minus powers of 2 injects into A).
3. Any set of positive integers with this sum-free property has upper density ≤ 1/2
   (shown by proving 2|B| ≤ n for any sum-free B ⊆ {1,...,n}).
-/

-- ============================================================================
-- Definitions
-- ============================================================================

/-- The set of positive integers whose odd part is ≡ 3 (mod 4).
    Equivalently, n is in A iff n ≡ 3 · 2^i (mod 2^{i+2}) for some i ≥ 0. -/
def A : Set ℕ := {n : ℕ | ∃ i q : ℕ, n = 2 ^ i * (4 * q + 3)}

noncomputable instance : DecidablePred (· ∈ A) := Classical.decPred _

/-- Counting function: |S ∩ {1,...,n}| -/
noncomputable def countIn (S : Set ℕ) (n : ℕ) : ℕ :=
  @Finset.card ℕ ((Finset.Icc 1 n).filter (fun x => @decide (x ∈ S) (Classical.dec _)))

/-- A set is power-of-2 sum-free if no two elements sum to a power of 2. -/
def pow2SumFree (S : Set ℕ) : Prop :=
  ∀ a ∈ S, ∀ b ∈ S, ∀ k : ℕ, a + b ≠ 2 ^ k

-- ============================================================================
-- Step 2: A is sum-free (no two elements sum to a power of 2)
-- ============================================================================

/-- A product 2^i * m where m is odd and m ≥ 3 is never a power of 2. -/
lemma pow2_mul_odd_ne_pow2 (i m : ℕ) (hm_odd : Odd m) (hm_ge : 3 ≤ m)
    (k : ℕ) : 2 ^ i * m ≠ 2 ^ k := by
  by_contra h_contra
  have h_div : 2 ^ (k - i) = m := by
    exact mul_left_cancel₀ (pow_ne_zero i two_ne_zero)
      (by rw [← pow_add, Nat.add_sub_of_le (le_of_not_gt fun hi => by
        nlinarith [pow_pos (zero_lt_two' ℕ) i,
          pow_lt_pow_right₀ (show 1 < 2 by decide) hi]), h_contra])
  grind

/-- Same-level case: sum has odd factor ≥ 3 -/
lemma sum_same_level_ne_pow2 (i p q : ℕ) (k : ℕ) :
    2 ^ i * (4 * p + 3) + 2 ^ i * (4 * q + 3) ≠ 2 ^ k := by
  have h_sum : 2 ^ i * (4 * p + 3) + 2 ^ i * (4 * q + 3) =
      2 ^ (i + 1) * (2 * (p + q) + 3) := by ring
  by_contra h_contra
  have h_odd : Odd (2 * (p + q) + 3) ∧ 3 ≤ 2 * (p + q) + 3 := by grind
  exact absurd (pow2_mul_odd_ne_pow2 (i + 1) (2 * (p + q) + 3) h_odd.1 h_odd.2 k) (by aesop)

/-- Different-level case: sum has odd factor ≥ 3 -/
lemma sum_diff_level_ne_pow2 (i j p q : ℕ) (h : i < j) (k : ℕ) :
    2 ^ i * (4 * p + 3) + 2 ^ j * (4 * q + 3) ≠ 2 ^ k := by
  have h_factor : 2 ^ i * (4 * p + 3) + 2 ^ j * (4 * q + 3) =
      2 ^ i * ((4 * p + 3) + 2 ^ (j - i) * (4 * q + 3)) := by
    rw [show j = i + (j - i) by rw [Nat.add_sub_cancel' h.le]]; ring_nf
    norm_num
  by_contra h_contra
  have h_inner_odd : Odd ((4 * p + 3) + 2 ^ (j - i) * (4 * q + 3)) := by grind
  have h_inner_ge : 3 ≤ (4 * p + 3) + 2 ^ (j - i) * (4 * q + 3) := by grind
  apply pow2_mul_odd_ne_pow2 i (4 * p + 3 + 2 ^ (j - i) * (4 * q + 3))
    h_inner_odd h_inner_ge k
  aesop

/-- **Step 2**: A is sum-free — no two elements of A sum to a power of 2. -/
theorem A_sumfree : ∀ a ∈ A, ∀ b ∈ A, ∀ k : ℕ, a + b ≠ 2 ^ k := by
  intro a ha b hb k
  obtain ⟨ia, pa, rfl⟩ := ha
  obtain ⟨ib, pb, rfl⟩ := hb
  rcases lt_trichotomy ia ib with h | rfl | h
  · exact sum_diff_level_ne_pow2 ia ib pa pb h k
  · exact sum_same_level_ne_pow2 ia pa pb k
  · rw [add_comm]; exact sum_diff_level_ne_pow2 ib ia pb pa h k

-- ============================================================================
-- Step 3: Optimality — any sum-free B ⊆ {1,...,n} has 2|B| ≤ n
-- ============================================================================

/-
If B ⊆ Icc (P-n) n is sum-free where P = 2^{l+1} and 2^l ≤ n < P,
then |B| ≤ n - 2^l.
-/
lemma pairing_bound (n l : ℕ) (hl : 2 ^ l ≤ n) (hn : n < 2 ^ (l + 1))
    (B : Finset ℕ) (hB : B ⊆ Finset.Icc (2 ^ (l + 1) - n) n)
    (hfree : ∀ a ∈ B, ∀ b ∈ B, ∀ k : ℕ, a + b ≠ 2 ^ k) :
    B.card ≤ n - 2 ^ l := by
      -- Define f : ℕ → ℕ by f(j) = if j < 2^l then j else 2^{l+1} - j.
      set f : ℕ → ℕ := fun j => if j < 2^l then j else 2^(l+1) - j;
      -- We show f maps B injectively into Finset.Icc (2^{l+1}-n) (2^l - 1).
      have h_inj : ∀ j ∈ B, f j ∈ Finset.Icc (2^(l+1) - n) (2^l - 1) := by
        grind +splitImp
      have h_inj_on : ∀ j₁ ∈ B, ∀ j₂ ∈ B, f j₁ = f j₂ → j₁ = j₂ := by
        grind
      have h_card : Finset.card B ≤ Finset.card (Finset.Icc (2^(l+1) - n) (2^l - 1)) := by
        exact Finset.card_le_card ( show B.image f ⊆ Finset.Icc ( 2 ^ ( l + 1 ) - n ) ( 2 ^ l - 1 ) from Finset.image_subset_iff.mpr h_inj ) |> le_trans ( by rw [ Finset.card_image_of_injOn h_inj_on ] )
      exact (by
      convert h_card using 1 ; norm_num [ Nat.pow_succ' ] at * ; omega;)

/-
**Step 3**: Any sum-free B ⊆ {1,...,n} satisfies 2|B| ≤ n.
-/
theorem sumfree_card_le : ∀ n : ℕ, ∀ B : Finset ℕ,
    B ⊆ Finset.Icc 1 n →
    (∀ a ∈ B, ∀ b ∈ B, ∀ k : ℕ, a + b ≠ 2 ^ k) →
    2 * B.card ≤ n := by
      intro n
      induction' n using Nat.strong_induction_on with n ih
      by_cases hn : n = 0;
      · aesop;
      · -- Let $l = \log_2 n$, so $2^l \le n < 2^{l+1}$.
        obtain ⟨l, hl⟩ : ∃ l, 2^l ≤ n ∧ n < 2^(l+1) := by
          exact ⟨ Nat.log 2 n, Nat.pow_le_of_le_log ( by positivity ) ( by linarith ), Nat.lt_pow_of_log_lt ( by linarith ) ( by linarith ) ⟩;
        -- Let $P = 2^{l+1}$, $m = P - n - 1$. Note $m < n$ since $P \le 2n$.
        set P := 2^(l+1)
        set m := P - n - 1
        have hm_lt_n : m < n := by
          grind;
        -- Split B into B₁ = B.filter (· ≤ m) and B₂ = B.filter (fun x => ¬(x ≤ m)).
        intros B hB hfree
        set B₁ := B.filter (· ≤ m)
        set B₂ := B.filter (fun x => ¬(x ≤ m));
        -- By induction (m < n), 2 * B₁.card ≤ m.
        have hB₁ : 2 * B₁.card ≤ m := by
          apply ih m hm_lt_n B₁;
          · exact fun x hx => Finset.mem_Icc.mpr ⟨ Finset.mem_Icc.mp ( hB ( Finset.mem_filter.mp hx |>.1 ) ) |>.1, Finset.mem_filter.mp hx |>.2 ⟩;
          · exact fun a ha b hb k => hfree a ( Finset.filter_subset _ _ ha ) b ( Finset.filter_subset _ _ hb ) k;
        -- By pairing_bound, B₂.card ≤ n - 2^l.
        have hB₂ : B₂.card ≤ n - 2^l := by
          apply pairing_bound n l hl.left hl.right B₂ (by
          simp +zetaDelta at *;
          exact fun x hx => Finset.mem_Icc.mpr ⟨ Nat.le_of_pred_lt ( Finset.mem_filter.mp hx |>.2 ), Finset.mem_Icc.mp ( hB ( Finset.mem_filter.mp hx |>.1 ) ) |>.2 ⟩) (by
          exact fun a ha b hb k => hfree a ( Finset.filter_subset _ _ ha ) b ( Finset.filter_subset _ _ hb ) k);
        -- Combine: 2 * B.card = 2 * B₁.card + 2 * B₂.card ≤ m + 2*(n - 2^l) = (2^{l+1} - n - 1) + 2*(n - 2^l) = n - 1 ≤ n.
        have h_combined : 2 * B.card = 2 * B₁.card + 2 * B₂.card := by
          rw [ ← mul_add, Finset.card_filter_add_card_filter_not ];
        lia

/-
============================================================================
Step 1: Lower bound for |A ∩ {1,...,n}| via injection argument
============================================================================

Every positive integer not in A and not a power of 2 has the form 2^i(4q+1)
    with q ≥ 1.
-/
lemma not_A_classification (n : ℕ) (hn : 0 < n) (hnA : n ∉ A) :
    (∃ k : ℕ, n = 2 ^ k) ∨ (∃ i q : ℕ, 1 ≤ q ∧ n = 2 ^ i * (4 * q + 1)) := by
  -- Use Nat.exists_eq_pow_mul_and_not_dvd to decompose n = 2^e * m where m is odd (¬2 ∣ m).
  obtain ⟨e, m, hm⟩ : ∃ e m : ℕ, n = 2^e * m ∧ Odd m := by
    exact ⟨ Nat.factorization n 2, n / 2 ^ Nat.factorization n 2, by rw [ Nat.mul_div_cancel' ( Nat.ordProj_dvd _ _ ) ], by rw [ Nat.odd_iff ] ; exact Nat.mod_two_ne_zero.mp fun con => absurd ( Nat.dvd_of_mod_eq_zero con ) ( Nat.not_dvd_ordCompl ( by norm_num ) ( by aesop ) ) ⟩;
  -- Since m is odd, m % 4 is either 1 or 3. If m % 4 = 3, write m = 4q + 3, then n = 2^e * (4q + 3) ∈ A, contradicting hnA. So m % 4 = 1.
  by_cases hm3 : m % 4 = 3;
  · exact False.elim <| hnA <| by rw [ hm.1 ] ; exact ⟨ e, m / 4, by nlinarith [ Nat.mod_add_div m 4, Nat.pow_le_pow_right two_pos ( show e ≥ 0 by positivity ) ] ⟩ ;
  · -- If m % 4 = 1, then m = 4q + 1 for some q ≥ 0.
    obtain ⟨q, hq⟩ : ∃ q : ℕ, m = 4 * q + 1 := by
      exact ⟨ m / 4, by obtain ⟨ k, rfl ⟩ := hm.2; omega ⟩;
    by_cases hq1 : q ≥ 1 <;> simp_all +decide;
    exact Or.inr ⟨ e, q, hq1, rfl ⟩

/-
The lower bound: n ≤ 2 * |A ∩ {1,...,n}| + ⌊log₂ n⌋ + 1.
-/
lemma A_count_lower (n : ℕ) :
    n ≤ 2 * countIn A n + Nat.log 2 n + 1 := by
  -- By definition of A, we know that every positive integer not in A and not a power of 2 is of the form 2^i*(4q+1) with q ≥ 1.
  have h_not_A : ∀ x ∈ Finset.Icc 1 n, x ∉ A → x ≠ 0 → (∃ k : ℕ, x = 2 ^ k) ∨ (∃ i q : ℕ, 1 ≤ q ∧ x = 2 ^ i * (4 * q + 1)) := by
    exact fun x hx₁ hx₂ hx₃ => not_A_classification x ( Finset.mem_Icc.mp hx₁ |>.1 ) hx₂;
  -- By definition of $A$, we know that for each $x$ in the set $\{1,...,n\} \setminus A$, there exists a unique $y \in A$ such that $x > y$.
  have h_inj : (Finset.filter (fun x => x ∉ A) (Finset.Icc 1 n)).card ≤ (Finset.filter (fun x => x ∈ A) (Finset.Icc 1 n)).card + (Nat.log 2 n + 1) := by
    -- By definition of $A$, we know that for each $x$ in the set $\{1,...,n\} \setminus A$, there exists a unique $y \in A$ such that $x > y$. Hence, we can pair each element in $\{1,...,n\} \setminus A$ with an element in $A$.
    have h_pair : Finset.filter (fun x => x ∉ A) (Finset.Icc 1 n) ⊆ Finset.image (fun x => 2 ^ (Nat.factorization x 2) * (4 * (Nat.floor ((x / 2 ^ (Nat.factorization x 2) - 1) / 4) + 1) + 1)) (Finset.filter (fun x => x ∈ A) (Finset.Icc 1 n)) ∪ Finset.image (fun k => 2 ^ k) (Finset.range (Nat.log 2 n + 1)) := by
      intro x hx;
      simp +zetaDelta at *;
      rcases h_not_A x hx.1.1 hx.1.2 hx.2 ( by linarith ) with ( ⟨ k, rfl ⟩ | ⟨ i, q, hq, rfl ⟩ );
      · exact Or.inr ⟨ k, Nat.le_log_of_pow_le ( by norm_num ) hx.1.2, rfl ⟩;
      · refine Or.inl ⟨ 2 ^ i * ( 4 * ( q - 1 ) + 3 ), ?_, ?_ ⟩ <;> rcases q with ( _ | q ) <;> simp_all +decide [ Nat.factorization_eq_zero_of_not_dvd, Nat.dvd_iff_mod_eq_zero, Nat.add_mod, Nat.mul_mod ];
        · exact ⟨ ⟨ Nat.mul_pos ( pow_pos ( by decide ) _ ) ( by linarith ), by nlinarith [ pow_pos ( by decide : 0 < 2 ) i ] ⟩, ⟨ i, q, rfl ⟩ ⟩;
        · norm_num [ Nat.add_div ];
    refine le_trans ( Finset.card_le_card h_pair ) ?_;
    grind +revert;
  convert add_le_add_left h_inj ( Finset.card ( Finset.filter ( fun x => x ∈ A ) ( Finset.Icc 1 n ) ) ) using 1 ; simp +arith +decide [ Finset.filter_not, Finset.card_sdiff ];
  · rw [ Finset.inter_eq_left.mpr fun x hx => by aesop ] ; rw [ add_tsub_cancel_of_le ] ; exact le_trans ( Finset.card_filter_le _ _ ) ( by simp ) ;
  · unfold countIn; ring_nf;
    grind

-- ============================================================================
-- Step 1b: A has natural density 1/2
-- ============================================================================

/-- Upper bound on countIn from sumfree_card_le. -/
lemma A_count_upper (n : ℕ) : 2 * countIn A n ≤ n := by
  unfold countIn
  apply sumfree_card_le n
  · exact Finset.filter_subset _ _
  · intro a ha b hb
    have ha' : a ∈ A := by simpa using (Finset.mem_filter.mp ha).2
    have hb' : b ∈ A := by simpa using (Finset.mem_filter.mp hb).2
    exact A_sumfree a ha' b hb'

/-
The ratio (Nat.log 2 n + 1) / (2 * n) tends to 0.
-/
lemma log_div_tends_zero :
    Filter.Tendsto (fun n : ℕ => ((Nat.log 2 n : ℝ) + 1) / (2 * n))
      Filter.atTop (nhds 0) := by
  refine' squeeze_zero_norm' _ _;
  refine' fun n => ( Real.log n / Real.log 2 + 1 : ℝ ) / n;
  · norm_num [ div_eq_mul_inv ];
    refine' ⟨ 2, fun n hn => _ ⟩ ; rw [ abs_of_nonneg ( by positivity ) ] ; ring_nf ; norm_num;
    nlinarith [ inv_pos.mpr ( by positivity : 0 < ( n : ℝ ) ), show ( log 2 n : ℝ ) ≤ Real.log n * ( Real.log 2 ) ⁻¹ by rw [ ← div_eq_mul_inv, le_div_iff₀ ( Real.log_pos one_lt_two ) ] ; nth_rw 1 [ ← Real.log_rpow zero_lt_two ] ; exact Real.log_le_log ( by positivity ) ( by norm_cast; exact Nat.pow_log_le_self 2 <| by positivity ) ];
  · -- We'll use the fact that $\frac{\log n}{n}$ tends to $0$ as $n$ tends to infinity.
    have h_log : Filter.Tendsto (fun n : ℕ => (Real.log n : ℝ) / n) Filter.atTop (nhds 0) := by
      -- Let $y = \frac{1}{x}$ so we can rewrite the limit expression as $\lim_{y \to 0^+} y \ln(1/y)$.
      suffices h_change_var : Filter.Tendsto (fun y : ℝ => y * Real.log (1 / y)) (Filter.map (fun x => 1 / x) Filter.atTop) (nhds 0) by
        exact h_change_var.comp ( Filter.map_mono tendsto_natCast_atTop_atTop ) |> fun h => h.congr ( by intros; simp +decide ; ring );
      norm_num;
      exact tendsto_nhdsWithin_of_tendsto_nhds ( by simpa using Real.continuous_mul_log.neg.tendsto 0 );
    convert h_log.div_const ( Real.log 2 ) |> Filter.Tendsto.add <| tendsto_inv_atTop_nhds_zero_nat using 2 <;> ring

/-
A has natural density 1/2.
-/
theorem A_density_half :
    Filter.Tendsto (fun n : ℕ => (countIn A n : ℝ) / n)
      Filter.atTop (nhds (1 / 2 : ℝ)) := by
  -- To prove the both sides are equal, we can use the fact that if the numerator and denominator of a fraction tend to infinity, the fraction tends to the ratio of the limits.
  suffices h_bot : Filter.Tendsto (fun n ↦ (2 * (countIn A n) : ℝ) / n - 1) Filter.atTop (nhds 0) by
    convert h_bot.add_const 1 |> Filter.Tendsto.div_const <| 2 using 2 <;> ring;
  have log_div_tends_zero : Filter.Tendsto (fun n : ℕ => ((Nat.log 2 n : ℝ) + 1) / n) Filter.atTop (nhds 0) := by
    convert log_div_tends_zero.const_mul 2 using 2 <;> ring;
  refine' squeeze_zero_norm' _ log_div_tends_zero;
  filter_upwards [ Filter.eventually_gt_atTop 0 ] with n hn;
  rw [ Real.norm_eq_abs, abs_le ];
  field_simp;
  constructor <;> linarith [ show ( countIn A n : ℝ ) ≥ 0 by positivity, show ( countIn A n : ℝ ) ≤ n / 2 by exact le_div_iff₀' ( by positivity ) |>.2 <| mod_cast A_count_upper n, show ( n : ℝ ) ≤ 2 * countIn A n + Nat.log 2 n + 1 by exact mod_cast A_count_lower n ]


-- ============================================================================
-- Upper density ≤ 1/2 for any pow2SumFree set
-- ============================================================================

/-
Any pow2SumFree set S satisfies 2 * |S ∩ {1,...,n}| ≤ n for all n.
-/
lemma sumfree_countIn_le (S : Set ℕ) (hS : pow2SumFree S) (n : ℕ) :
    2 * countIn S n ≤ n := by
  convert sumfree_card_le n ( Finset.filter ( fun x => x ∈ S ) ( Finset.Icc 1 n ) ) ?_ ?_ using 1;
  convert rfl;
  rotate_left;
  exact Classical.decPred S;
  · grind;
  · grind +locals;
  · congr;
    grind

/-
The upper density of any pow2SumFree set is at most 1/2.
-/
theorem sumfree_upperDensity_le_half (S : Set ℕ) (hS : pow2SumFree S) :
    Filter.limsup (fun n : ℕ => (countIn S n : ℝ) / ↑n)
      Filter.atTop ≤ 1 / 2 := by
  refine' csInf_le _ _ <;> norm_num;
  · exact ⟨ 0, by rintro x ⟨ n, hn ⟩ ; exact le_trans ( by positivity ) ( hn _ le_rfl ) ⟩;
  · exact ⟨ 1, fun n hn => by rw [ div_le_div_iff₀ ] <;> norm_cast ; linarith [ sumfree_countIn_le S hS n ] ⟩

-- ============================================================================
-- Main result
-- ============================================================================

/-- **Main result**: There exists a set with natural density 1/2 that is
    power-of-2 sum-free, and every power-of-2 sum-free set has upper density
    at most 1/2. -/
theorem main_result :
    (∃ S : Set ℕ, pow2SumFree S ∧
      Filter.Tendsto (fun n : ℕ => (countIn S n : ℝ) / ↑n)
        Filter.atTop (nhds (1 / 2 : ℝ))) ∧
    (∀ S : Set ℕ, pow2SumFree S →
      Filter.limsup (fun n : ℕ => (countIn S n : ℝ) / ↑n)
        Filter.atTop ≤ 1 / 2) :=
  ⟨⟨A, A_sumfree, A_density_half⟩, fun S hS => sumfree_upperDensity_le_half S hS⟩

#print axioms main_result

-- ============================================================================
-- More general upper bound
-- ============================================================================

/-
Pigeonhole principle for sums: if `A ⊆ {low, ..., S - low}` and
    `2 * |A| + 2 * low ≥ S + 2`, then some two elements of `A` sum to `S`.
-/
lemma sum_pair_pigeonhole (S low : ℕ) (hlow : 1 ≤ low) (hSlow : 2 * low ≤ S)
    (A : Finset ℕ) (hA : A ⊆ Finset.Icc low (S - low))
    (hcard : 2 * A.card + 2 * low ≥ S + 2) :
    ∃ a ∈ A, ∃ b ∈ A, a + b = S := by
  by_contra h_contra;
  -- Consider the set $B = \{S - a \mid a \in A\}$.
  set B : Finset ℕ := Finset.image (fun a => S - a) A;
  -- Since $A$ and $B$ are disjoint subsets of $\{low, ..., S - low\}$, we have $|A \cup B| = |A| + |B|$.
  have h_union : (A ∪ B).card = A.card + B.card := by
    apply Finset.card_union_of_disjoint;
    exact Finset.disjoint_left.mpr fun x hx hx' => h_contra <| by obtain ⟨ y, hy, hy' ⟩ := Finset.mem_image.mp hx'; exact ⟨ y, hy, x, hx, by linarith [ Nat.sub_add_cancel <| show y ≤ S from le_trans ( Finset.mem_Icc.mp ( hA hy ) |>.2 ) ( Nat.sub_le _ _ ) ] ⟩ ;
  -- Since $B$ is a subset of $\{low, ..., S - low\}$, we have $|B| = |A|$.
  have hB_card : B.card = A.card := by
    exact Finset.card_image_of_injOn fun x hx y hy hxy => by rw [ tsub_right_inj ] at hxy <;> linarith [ Finset.mem_Icc.mp ( hA hx ), Finset.mem_Icc.mp ( hA hy ), Nat.sub_add_cancel ( by linarith : low ≤ S ) ] ;
  have h_union_subset : A ∪ B ⊆ Finset.Icc low (S - low) := by
    exact Finset.union_subset hA ( Finset.image_subset_iff.mpr fun x hx => Finset.mem_Icc.mpr ⟨ Nat.le_sub_of_add_le <| by linarith [ Finset.mem_Icc.mp <| hA hx, Nat.sub_add_cancel <| show low ≤ S from by linarith ], Nat.sub_le_sub_left ( by linarith [ Finset.mem_Icc.mp <| hA hx ] ) _ ⟩ );
  have := Finset.card_mono h_union_subset; simp_all +decide ; omega;

/-
**Main resultv2** For any infinite strictly increasing sequence `s` of positive
    integers satisfying `s(k+1) ≤ 2·s(k) + 2`, and any `A ⊆ {1,…,n}` with
    `2|A| > n + s(0)`, there exist `a, b ∈ A` and `i` such that `a + b = s(i)`.
-/
theorem general_upper_bound (s : ℕ → ℕ) (hs_pos : ∀ k, 0 < s k)
    (hs_mono : StrictMono s) (hs_growth : ∀ k, s (k + 1) ≤ 2 * s k + 2)
    (n : ℕ) (hn : 0 < n) (A : Finset ℕ) (hA_sub : A ⊆ Finset.Icc 1 n)
    (hA_card : 2 * A.card > n + s 0) :
    ∃ i, ∃ a ∈ A, ∃ b ∈ A, a + b = s i := by
  by_contra h_contra;
  -- By induction on $n$, we can show that for any $n$, if $2|A| > n + s(0)$, then there exist $a, b \in A$ such that $a + b = s(i)$ for some $i$.
  induction' n using Nat.strong_induction_on with n ih generalizing A;
  -- Let $k$ be such that $s(k) \leq n < s(k+1)$.
  obtain ⟨k, hk⟩ : ∃ k, s k ≤ n ∧ n < s (k + 1) := by
    have h_seq : ∃ k, s k ≤ n ∧ n < s (k + 1) := by
      have h_unbounded : ∀ M : ℕ, ∃ k, s k > M := by
        exact fun M => ⟨ _, hs_mono.id_le _ ⟩
      contrapose! h_unbounded;
      exact ⟨ n, fun k => Nat.recOn k ( by linarith [ hs_pos 0, show s 0 ≤ n from le_of_not_gt fun h => by have := Finset.card_le_card hA_sub; norm_num at *; linarith [ hs_pos 0 ] ] ) h_unbounded ⟩;
    exact h_seq;
  -- Let $m = s(k+1) - n$. Then $m \geq 1$.
  set m := s (k + 1) - n with hm_def
  have hm_pos : 1 ≤ m := by
    exact Nat.sub_pos_of_lt hk.2;
  -- Consider two cases: $n = s(k)$ and $n \neq s(k)$.
  by_cases h_case : n = s k;
  · -- If $s(k) \geq 2$, then apply the pigeonhole principle to $s(k)$.
    by_cases h_sk_ge_2 : 2 ≤ s k;
    · -- Let $A' = A \setminus \{s(k)\}$. Then $|A'| \geq |A| - 1$.
      set A' := A \ {s k} with hA'_def
      have hA'_card : A'.card ≥ A.card - 1 := by
        grind;
      -- Since $A'$ is a subset of $\{1, ..., s(k) - 1\}$, we can apply the pigeonhole principle.
      have hA'_subset : A' ⊆ Finset.Icc 1 (s k - 1) := by
        grind;
      have h_pigeonhole : ∃ a ∈ A', ∃ b ∈ A', a + b = s k := by
        apply sum_pair_pigeonhole (s k) 1 (by linarith) (by linarith) A' hA'_subset;
        grind;
      grind +locals;
    · interval_cases _ : s k <;> simp_all +decide;
      grind;
  · -- Consider two cases: $m = 1$ and $m > 1$.
    by_cases h_case2 : m = 1;
    · -- Apply the pigeonhole principle to find $a, b \in A$ such that $a + b = s(k+1)$.
      have h_pigeonhole : ∃ a ∈ A, ∃ b ∈ A, a + b = s (k + 1) := by
        apply sum_pair_pigeonhole (s (k + 1)) 1 (by norm_num) (by
        grind +splitIndPred) A (by
        exact fun x hx => Finset.mem_Icc.mpr ⟨ Finset.mem_Icc.mp ( hA_sub hx ) |>.1, Nat.le_sub_one_of_lt ( lt_of_le_of_lt ( Finset.mem_Icc.mp ( hA_sub hx ) |>.2 ) hk.2 ) ⟩) (by
        lia);
      exact h_contra ⟨ _, _, h_pigeonhole.choose_spec.1, _, h_pigeonhole.choose_spec.2.choose_spec.1, h_pigeonhole.choose_spec.2.choose_spec.2 ⟩;
    · -- Let $A_1 = A \cap \{1, \ldots, m-1\}$ and $A_2 = A \cap \{m, \ldots, n\}$.
      set A1 := A.filter (fun x => x ≤ m - 1) with hA1_def
      set A2 := A.filter (fun x => m ≤ x) with hA2_def;
      -- If $2|A_1| > (m-1) + s(0)$, then apply the induction hypothesis to $A_1$.
      by_cases h_case3 : 2 * A1.card > (m - 1) + s 0;
      · specialize ih ( m - 1 ) ?_ ?_ A1 ?_ ?_ ?_ <;> norm_num at *;
        · grind +suggestions;
        · exact lt_of_le_of_ne hm_pos ( Ne.symm h_case2 );
        · exact fun x hx => Finset.mem_Icc.mpr ⟨ Finset.mem_Icc.mp ( hA_sub ( Finset.mem_filter.mp hx |>.1 ) ) |>.1, Finset.mem_filter.mp hx |>.2 ⟩;
        · grind;
        · exact fun x y hy z hz => h_contra x y ( Finset.mem_filter.mp hy |>.1 ) z ( Finset.mem_filter.mp hz |>.1 );
      · -- Since $2|A_2| + 2m \geq s(k+1) + 2$, we can apply the pigeonhole principle to find $a, b \in A_2$ such that $a + b = s(k+1)$.
        have h_pigeonhole : ∃ a ∈ A2, ∃ b ∈ A2, a + b = s (k + 1) := by
          apply sum_pair_pigeonhole;
          exact hm_pos;
          · grind;
          · grind +extAll;
          · have h_card_A2 : A1.card + A2.card = A.card := by
              rw [ Finset.card_filter, Finset.card_filter ];
              rw [ ← Finset.sum_add_distrib, Finset.card_eq_sum_ones ];
              grind;
            omega;
        exact h_contra ⟨ k + 1, by aesop ⟩

#print axioms general_upper_bound

-- ============================================================================
-- Corollary: A+A hits S infinitely often when upper density > 1/2
-- ============================================================================

/-
Removing elements in {1,...,M} from A: for M ≤ n, the count splits.
-/
lemma countIn_sdiff_Icc (A : Set ℕ) (M n : ℕ) (hn : M ≤ n) :
    countIn (A \ Set.Icc 1 M) n = countIn A n - countIn A M := by
      refine' eq_tsub_of_add_eq _;
      unfold countIn;
      rw [ ← Finset.card_union_of_disjoint ];
      · congr with x;
        grind;
      · simp +contextual [ Finset.disjoint_left ]

/-
If upper density > 1/2, then for any constant c, there exist
    arbitrarily large n with 2 * countIn A n > n + c.
-/
lemma upper_density_exceeds (A : Set ℕ)
    (hA_density : 1 / 2 < Filter.limsup (fun n : ℕ => (countIn A n : ℝ) / ↑n) Filter.atTop)
    (c : ℕ) : ∃ n : ℕ, 0 < n ∧ 2 * countIn A n > n + c := by
      contrapose! hA_density;
      refine' le_of_forall_pos_le_add fun ε ε_pos => _;
      refine' csInf_le _ _ <;> norm_num;
      · exact ⟨ 0, by rintro x ⟨ n, hn ⟩ ; exact le_trans ( by positivity ) ( hn _ le_rfl ) ⟩;
      · exact ⟨ ⌈ε⁻¹ * ( c + 1 ) ⌉₊ + 1, fun n hn => by rw [ div_le_iff₀ ] <;> nlinarith [ Nat.le_ceil ( ε⁻¹ * ( c + 1 ) ), mul_inv_cancel₀ ( ne_of_gt ε_pos ), show ( n : ℝ ) ≥ ⌈ε⁻¹ * ( c + 1 ) ⌉₊ + 1 by exact_mod_cast hn, show ( countIn A n : ℝ ) ≤ ( n + c ) / 2 by exact by rw [ le_div_iff₀ ] <;> norm_cast ; linarith [ hA_density n ( by linarith ) ] ] ⟩

theorem general_upper_bound_unbounded
    (s : ℕ → ℕ) (hs_pos : ∀ k, 0 < s k)
    (hs_mono : StrictMono s) (hs_growth : ∀ k, s (k + 1) ≤ 2 * s k + 2)
    (A : Set ℕ)
    (hA_density : 1 / 2 < Filter.limsup (fun n : ℕ => (countIn A n : ℝ) / ↑n) Filter.atTop) :
    ∀ M : ℕ, ∃ i, M < s i ∧ ∃ a ∈ A, ∃ b ∈ A, a + b = s i := by
  intro M
  have := upper_density_exceeds A hA_density (s 0 + 2 * M)
  obtain ⟨n, hn₁, hn₂⟩ := this
  obtain ⟨B, hB⟩ :
      ∃ B : Finset ℕ,
        B ⊆ Finset.Icc 1 n ∧
        B.card = countIn (A \ Set.Icc 1 M) n ∧
        ∀ x ∈ B, x ∈ A ∧ x > M := by
    grind +locals
  have hB_card : 2 * B.card > n + s 0 := by
    have hB_card : countIn (A \ Set.Icc 1 M) n = countIn A n - countIn A M := by
      apply countIn_sdiff_Icc
      contrapose! hn₂
      exact le_trans
        (mul_le_mul_of_nonneg_left
          (show countIn A n ≤ n from le_trans (Finset.card_filter_le _ _) (by simp))
          zero_le_two)
        (by linarith [hs_pos 0])
    have hB_card : countIn A M ≤ M := by
      exact le_trans (Finset.card_filter_le _ _) (by simp)
    omega
  grind +suggestions

/-
**Corollary**: For any sequence `s` of positive integers with
    `s(k+1) ≤ 2·s(k) + 2` and any set `A` of positive integers with
    upper density > 1/2, the sumset `A + A` contains infinitely many
    elements of `s`.
-/
theorem general_upper_bound_infinite
    (s : ℕ → ℕ) (hs_pos : ∀ k, 0 < s k)
    (hs_mono : StrictMono s) (hs_growth : ∀ k, s (k + 1) ≤ 2 * s k + 2)
    (A : Set ℕ)
    (hA_density : 1 / 2 < Filter.limsup (fun n : ℕ => (countIn A n : ℝ) / ↑n) Filter.atTop) :
    Set.Infinite {i : ℕ | ∃ a ∈ A, ∃ b ∈ A, a + b = s i} := by
  classical
  by_contra hfin
  have hfin' : Set.Finite {i : ℕ | ∃ a ∈ A, ∃ b ∈ A, a + b = s i} :=
    Set.not_infinite.mp hfin
  rcases hfin'.bddAbove with ⟨M, hM⟩
  obtain ⟨i, hi, a, haA, b, hbA, hab⟩ :=
    general_upper_bound_unbounded s hs_pos hs_mono hs_growth A hA_density (s M)
  have hi_mem : i ∈ {i : ℕ | ∃ a ∈ A, ∃ b ∈ A, a + b = s i} := by
    exact ⟨a, haA, b, hbA, hab⟩
  have hi_le : i ≤ M := hM hi_mem
  have hsi_le : s i ≤ s M := hs_mono.monotone hi_le
  exact (not_lt_of_ge hsi_le) hi

#print axioms general_upper_bound_infinite

noncomputable section greedy
open Finset Filter Nat Classical
open scoped Topology

-- ============================================================================
-- Greedy approach
-- ============================================================================

def inA (m : ℕ) : Prop :=
  m ≥ 1 ∧ (∀ k : ℕ, 2 * m ≠ 2 ^ k) ∧
  (∀ a : ℕ, 1 ≤ a → a < m → inA a → ∀ k : ℕ, m + a ≠ 2 ^ k)
termination_by m

/-- The set A = {m | inA m} -/
def setA : Set ℕ := {m | inA m}

-- ============================================================================
-- Basic properties from the definition
-- ============================================================================

lemma inA_pos {m : ℕ} (h : inA m) : m ≥ 1 := by
  unfold inA at h; exact h.1

lemma inA_not_two_mul_pow {m : ℕ} (h : inA m) (k : ℕ) : 2 * m ≠ 2 ^ k := by
  unfold inA at h; exact h.2.1 k

lemma inA_no_pair {m a : ℕ} (hm : inA m) (ha1 : 1 ≤ a) (ha2 : a < m) (ha : inA a) (k : ℕ) :
    m + a ≠ 2 ^ k := by
  unfold inA at hm; exact hm.2.2 a ha1 ha2 ha k

lemma not_inA_pow2 (n : ℕ) : ¬ inA (2 ^ n) := by
  intro h; exact inA_not_two_mul_pow h (n + 1) (by ring)

/-- To show inA m, it suffices to show the three conditions -/
lemma inA_of_conditions {m : ℕ} (h1 : m ≥ 1) (h2 : ∀ k : ℕ, 2 * m ≠ 2 ^ k)
    (h3 : ∀ a : ℕ, 1 ≤ a → a < m → inA a → ∀ k : ℕ, m + a ≠ 2 ^ k) : inA m := by
  unfold inA; exact ⟨h1, h2, h3⟩

-- ============================================================================
-- Sum-free property
-- ============================================================================

/-- **Sum-free property**: No two elements of A sum to a power of 2. -/
theorem sumFree {a b : ℕ} (ha : inA a) (hb : inA b) (k : ℕ) : a + b ≠ 2 ^ k := by
  by_cases hab : a < b
  · rw [add_comm]; exact inA_no_pair hb (inA_pos ha) hab ha k
  · push_neg at hab
    by_cases hab' : b < a
    · exact inA_no_pair ha (inA_pos hb) hab' hb k
    · push_neg at hab'
      have heq : a = b := le_antisymm hab' hab
      subst heq
      intro h
      exact inA_not_two_mul_pow ha k (by omega)

/-
============================================================================
Key structural lemma: unique pairing with powers of 2
============================================================================

For m in (2^n, 2^(n+1)) and 1 ≤ a < m, if m + a = 2^k then k = n + 1.
-/
lemma unique_power {m a n : ℕ} (hm1 : 2 ^ n < m) (hm2 : m < 2 ^ (n + 1))
    (ha1 : 1 ≤ a) (ha2 : a < m) {k : ℕ} (hk : m + a = 2 ^ k) : k = n + 1 := by
  refine' Nat.le_antisymm _ _;
  · contrapose! hk;
    -- If $n + 1 < k$, then $2^k \geq 2^{n+2}$.
    have hk_ge : 2 ^ k ≥ 2 ^ (n + 2) := by
      exact pow_le_pow_right₀ ( by decide ) hk;
    grind;
  · exact Nat.succ_le_of_lt ( Nat.lt_of_not_ge fun h => by linarith [ Nat.pow_le_pow_right two_pos h ] )

/-
**Structural lemma**: For m in (2^n, 2^(n+1)), m ∈ A iff 2^(n+1) - m ∉ A.
-/
theorem structural {m n : ℕ} (hm1 : 2 ^ n < m) (hm2 : m < 2 ^ (n + 1)) :
    inA m ↔ ¬ inA (2 ^ (n + 1) - m) := by
  constructor;
  · grind +suggestions;
  · intro h_not_inA
    apply inA_of_conditions
    exact hm1.le.trans_lt' (by norm_num)
    intro k hk
    have h_contra : m = 2 ^ (k - 1) := by
      cases k <;> simp_all +decide [ pow_succ' ]
    exact (by
    rcases k with ( _ | _ | k ) <;> simp_all +decide [ pow_succ' ];
    norm_num [ ← pow_succ' ] at * ; linarith [ Nat.pow_le_pow_right ( by decide : 1 ≤ 2 ) ( show n ≥ k + 1 from Nat.succ_le_of_lt ( Nat.lt_of_not_ge fun h => by linarith [ Nat.pow_le_pow_right ( by decide : 1 ≤ 2 ) h ] ) ) ] ;)
    intro a ha1 ha2 ha3 k hk
    have h_contra : a = 2 ^ (n + 1) - m := by
      have h_contra : k = n + 1 := by
        apply unique_power hm1 hm2 ha1 ha2 hk
      rw [h_contra] at hk
      linarith [Nat.sub_add_cancel hm2.le]
    exact (by
    aesop)

-- ============================================================================
-- Counting
-- ============================================================================

/-- Count of elements of A in {1, ..., N} -/
def countA (N : ℕ) : ℕ := ((Icc 1 N).filter (fun m => inA m)).card

/-
countA is monotone
-/
lemma countA_mono {M N : ℕ} (h : M ≤ N) : countA M ≤ countA N := by
  exact Finset.card_mono <| Finset.filter_subset_filter _ <| Finset.Icc_subset_Icc_right h

/-
============================================================================
Functional equation for countA
============================================================================

Difference of countA over an interval
-/
lemma countA_diff {a b : ℕ} (h : a ≤ b) :
    countA b - countA a = ((Icc (a + 1) b).filter (fun m => inA m)).card := by
  unfold countA;
  rw [ tsub_eq_of_eq_add_rev ];
  rw [ ← Finset.card_union_of_disjoint ];
  · congr 1 with x ; norm_num;
    grind;
  · exact Finset.disjoint_left.mpr fun x hx₁ hx₂ => by linarith [ Finset.mem_Icc.mp ( Finset.mem_filter.mp hx₁ |>.1 ), Finset.mem_Icc.mp ( Finset.mem_filter.mp hx₂ |>.1 ) ] ;

/-
Generalized split of countA at a power of 2.
    For 2^j ≤ N ≤ 2^(j+1) - 1:
    countA(N) = countA(2^j - 1) + |A ∩ [2^j + 1, N]|
-/
lemma countA_split_general {j N : ℕ} (hN1 : 2^j ≤ N) :
    countA N = countA (2^j - 1) +
    ((Icc (2^j + 1) N).filter (fun m => inA m)).card := by
  have h_split : (Icc 1 N).filter (fun m => inA m) = (Icc 1 (2 ^ j - 1)).filter (fun m => inA m) ∪ (Icc (2 ^ j + 1) N).filter (fun m => inA m) := by
    ext m;
    by_cases hm : m = 2 ^ j <;> simp_all +decide ;
    · exact fun h _ => absurd h ( not_inA_pow2 j );
    · grind +revert;
  rw [ countA, countA, h_split, Finset.card_union_of_disjoint ];
  exact Finset.disjoint_left.mpr fun x hx₁ hx₂ => by linarith [ Finset.mem_Icc.mp ( Finset.mem_filter.mp hx₁ |>.1 ), Finset.mem_Icc.mp ( Finset.mem_filter.mp hx₂ |>.1 ), Nat.sub_add_cancel ( Nat.one_le_pow j 2 zero_lt_two ) ] ;

/-
The A-count in [2^j+1, N] plus the A-count in [2^(j+1)-N, 2^j-1] equals N - 2^j.
    This follows from the structural lemma: m ↦ 2^(j+1) - m is a bijection
    sending A-elements to non-A-elements.
-/
lemma count_upper_plus_lower {j N : ℕ} (hN1 : 2^j ≤ N) (hN2 : N ≤ 2^(j+1) - 1) :
    ((Icc (2^j + 1) N).filter (fun m => inA m)).card +
    ((Icc (2^(j+1) - N) (2^j - 1)).filter (fun m => inA m)).card = N - 2^j := by
  -- By the structural lemma, m ↦ 2^(j+1) - m is a bijection from [2^j + 1, N] to [2^(j+1)-N, 2^j-1].
  have h_bij : Finset.image (fun m => 2^(j+1) - m) (Finset.Icc (2^j + 1) N) = Finset.Icc (2^(j+1) - N) (2^j - 1) := by
    ext m;
    simp +zetaDelta at *;
    constructor;
    · grind;
    · intro hm;
      use 2^(j+1) - m;
      grind;
  rw [ ← h_bij, Finset.card_filter, Finset.card_filter ];
  rw [ Finset.sum_image ] <;> norm_num;
  · rw [ Finset.card_filter, Finset.card_filter ];
    rw [ ← Finset.sum_add_distrib, Finset.sum_congr rfl fun x hx => ?_ ];
    rotate_left;
    use fun x => 1;
    · split_ifs <;> simp_all +decide;
      · exact absurd ( sumFree ‹inA x› ‹inA ( 2 ^ ( j + 1 ) - x ) › ( j + 1 ) ) ( by rw [ Nat.add_sub_of_le ( by linarith [ Nat.sub_add_cancel ( Nat.one_le_pow ( j + 1 ) 2 zero_lt_two ) ] ) ] ; norm_num );
      · have := structural ( show 2 ^ j < x from hx.1 ) ( show x < 2 ^ ( j + 1 ) from lt_of_le_of_lt hx.2 ( lt_of_le_of_lt hN2 ( Nat.sub_lt ( by norm_num ) ( by norm_num ) ) ) ) ; aesop;
    · simp +arith +decide;
  · exact fun x hx y hy hxy => by rw [ tsub_right_inj ] at hxy <;> linarith [ hx.1, hx.2, hy.1, hy.2, Nat.sub_add_cancel ( show 1 ≤ 2 ^ ( j + 1 ) from Nat.one_le_pow _ _ ( by decide ) ) ] ;

/-
**Functional equation**: For 2^j ≤ N ≤ 2^(j+1) - 1:
    countA(N) = (N - 2^j) + countA(2^(j+1) - 1 - N)
-/
theorem countA_functional {j N : ℕ} (hN1 : 2^j ≤ N) (hN2 : N ≤ 2^(j+1) - 1) :
    countA N = (N - 2^j) + countA (2^(j+1) - 1 - N) := by
  have h_split : countA N = countA (2^j - 1) + ((Icc (2^j + 1) N).filter (fun m => inA m)).card := by
    exact countA_split_general hN1;
  have h_upper_plus_lower : ((Icc (2^j + 1) N).filter (fun m => inA m)).card +
                            ((Icc (2^(j+1) - N) (2^j - 1)).filter (fun m => inA m)).card = N - 2^j := by
                              exact count_upper_plus_lower hN1 hN2;
  have h_lower_count : ((Icc (2^(j+1) - N) (2^j - 1)).filter (fun m => inA m)).card =
                         countA (2^j - 1) - countA (2^(j+1) - N - 1) := by
                           convert rfl;
                           convert countA_diff _ using 1;
                           · grind +extAll;
                           · omega;
  rw [ show 2 ^ ( j + 1 ) - 1 - N = 2 ^ ( j + 1 ) - N - 1 by omega ];
  linarith [ Nat.sub_add_cancel ( show countA ( 2 ^ j - 1 ) ≥ countA ( 2 ^ ( j + 1 ) - N - 1 ) from countA_mono <| by omega ) ]

/-
============================================================================
Density
============================================================================

The "gap" g(N) = N - 2·countA(N) satisfies g(N) = g(M) + 1
    for M = 2^(j+1) - 1 - N < N, and g(0) = 0.
-/
lemma gap_recurrence {j N : ℕ} (hN1 : 2^j ≤ N) (hN2 : N ≤ 2^(j+1) - 1) :
    N - 2 * countA N = (2^(j+1) - 1 - N) - 2 * countA (2^(j+1) - 1 - N) + 1 := by
  rw [ countA_functional hN1 hN2 ];
  -- By definition of $countA$, we know that $countA(k) \leq k / 2$ for any $k$.
  have h_countA_le_half : ∀ k : ℕ, countA k ≤ k / 2 := by
    intro k
    induction' k using Nat.strong_induction_on with k ih;
    by_cases hk : k = 0;
    · aesop;
    · -- Let $j$ be such that $2^j \leq k < 2^{j+1}$.
      obtain ⟨j, hj⟩ : ∃ j, 2^j ≤ k ∧ k < 2^(j+1) := by
        exact ⟨ Nat.log 2 k, Nat.pow_le_of_le_log ( by positivity ) ( by linarith ), Nat.lt_pow_of_log_lt ( by linarith ) ( by linarith ) ⟩;
      -- Using the functional equation, we have $countA(k) = (k - 2^j) + countA(2^{j+1} - 1 - k)$.
      have h_fun_eq : countA k = (k - 2^j) + countA (2^(j+1) - 1 - k) := by
        apply countA_functional; exact hj.left; exact Nat.le_sub_one_of_lt hj.right;
      grind;
  grind

/-
2·countA(N) ≤ N for all N
-/
theorem two_countA_le (N : ℕ) : 2 * countA N ≤ N := by
  induction' N using Nat.strong_induction_on with N ih;
  by_cases hN : N = 0;
  · aesop;
  · -- For N ≥ 1: find j with 2^j ≤ N and N ≤ 2^(j+1) - 1 (j = Nat.log 2 N).
    obtain ⟨j, hj1, hj2⟩ : ∃ j, 2^j ≤ N ∧ N ≤ 2^(j+1) - 1 := by
      exact ⟨ Nat.log 2 N, Nat.pow_le_of_le_log ( by positivity ) ( by linarith ), Nat.le_sub_one_of_lt ( Nat.lt_pow_of_log_lt ( by linarith ) ( by linarith ) ) ⟩;
    rw [ countA_functional hj1 hj2 ];
    grind

/-
The gap N - 2·countA(N) is at most Nat.log 2 N + 1
-/
theorem gap_le_log (N : ℕ) (hN : N ≥ 1) : N - 2 * countA N ≤ Nat.log 2 N + 1 := by
  induction' N using Nat.strong_induction_on with N ih;
  -- By gap_recurrence: N - 2*countA(N) = M - 2*countA(M) + 1, where M = 2^(j+1) - 1 - N.
  obtain ⟨j, hj⟩ : ∃ j, 2^j ≤ N ∧ N < 2^(j+1) := by
    exact ⟨ Nat.log 2 N, Nat.pow_le_of_le_log ( by linarith ) ( by linarith ), Nat.lt_pow_of_log_lt ( by linarith ) ( by linarith ) ⟩
  have hM : N - 2 * countA N = (2^(j+1) - 1 - N) - 2 * countA (2^(j+1) - 1 - N) + 1 := by
    apply gap_recurrence hj.left (Nat.le_sub_one_of_lt hj.right);
  by_cases hM_zero : 2^(j+1) - 1 - N = 0;
  · grind;
  · have hM_lt : 2^(j+1) - 1 - N < 2^j := by
      omega;
    have hM_log : Nat.log 2 (2^(j+1) - 1 - N) < j := by
      exact Nat.log_lt_of_lt_pow ( by positivity ) hM_lt;
    have hM_log : Nat.log 2 N ≥ j := by
      exact Nat.le_log_of_pow_le ( by decide ) hj.1;
    grind

/-
A has natural density 1/2
-/
theorem density_half :
    Tendsto (fun N => (countA N : ℝ) / (N : ℝ)) atTop (nhds (1 / 2 : ℝ)) := by
  -- Apply the squeeze theorem to conclude the proof.
  have h_squeeze : ∀ ε > 0, ∃ N₀ : ℕ, ∀ N ≥ N₀, |(countA N : ℝ) / N - 1 / 2| < ε := by
    -- For any ε > 0, we can find an N₀ such that for all N ≥ N₀, (Nat.log 2 N + 1) / (2 * N) < ε.
    have h_log_div : Filter.Tendsto (fun N : ℕ => (Nat.log 2 N + 1 : ℝ) / (2 * N)) Filter.atTop (nhds 0) := by
      -- We'll use the fact that $\log_2 N$ grows slower than any linear function in $N$.
      have h_log_growth : Filter.Tendsto (fun N : ℕ => (Nat.log 2 N : ℝ) / N) Filter.atTop (nhds 0) := by
        -- We can use the change of variables $k = \log_2 N$ to transform the limit expression.
        suffices h_log : Filter.Tendsto (fun k : ℕ => (k : ℝ) / 2 ^ k) Filter.atTop (nhds 0) by
          have h_log : Filter.Tendsto (fun N : ℕ => (Nat.log 2 N : ℝ) / 2 ^ (Nat.log 2 N)) Filter.atTop (nhds 0) := by
            exact h_log.comp ( Filter.tendsto_atTop_atTop.mpr fun k => ⟨ 2 ^ k, fun n hn => Nat.le_log_of_pow_le ( by norm_num ) hn ⟩ );
          refine' squeeze_zero_norm' _ h_log;
          filter_upwards [ Filter.eventually_gt_atTop 0 ] with n hn using by rw [ Real.norm_of_nonneg ( by positivity ) ] ; gcongr ; norm_cast ; exact Nat.pow_log_le_self 2 hn.ne';
        refine' squeeze_zero_norm' _ tendsto_inv_atTop_nhds_zero_nat;
        norm_num;
        exact ⟨ 8, fun n hn => by rw [ inv_eq_one_div, div_le_div_iff₀ ] <;> norm_cast <;> induction hn <;> norm_num [ Nat.pow_succ ] at * ; nlinarith ⟩;
      convert h_log_growth.div_const 2 |> Filter.Tendsto.add <| tendsto_inv_atTop_nhds_zero_nat.div_const 2 using 2 <;> ring;
    -- By the definition of absolute value, we know that $|a - b| < ε$ if and only if $-ε < a - b < ε$.
    intros ε hε_pos
    have h_abs : ∀ N ≥ 1, |(countA N : ℝ) / N - 1 / 2| ≤ (Nat.log 2 N + 1 : ℝ) / (2 * N) := by
      intros N hN_pos
      have h_abs : (countA N : ℝ) / N ≥ 1 / 2 - (Nat.log 2 N + 1 : ℝ) / (2 * N) := by
        field_simp;
        have := gap_le_log N hN_pos;
        exact sub_le_iff_le_add'.mpr ( by norm_cast; omega );
      rw [ abs_le ];
      constructor <;> nlinarith [ show ( countA N : ℝ ) ≤ N / 2 by exact le_div_iff₀' ( by positivity ) |>.2 <| mod_cast two_countA_le N, show ( N : ℝ ) ≥ 1 by exact_mod_cast hN_pos, div_mul_cancel₀ ( countA N : ℝ ) ( by positivity : ( N : ℝ ) ≠ 0 ), div_mul_cancel₀ ( ( Nat.log 2 N + 1 : ℝ ) ) ( by positivity : ( 2 * N : ℝ ) ≠ 0 ) ];
    exact Filter.eventually_atTop.mp ( h_log_div.eventually ( gt_mem_nhds hε_pos ) ) |> fun ⟨ N₀, hN₀ ⟩ ↦ ⟨ N₀ + 1, fun N hN ↦ lt_of_le_of_lt ( h_abs N ( by linarith ) ) ( hN₀ N ( by linarith ) ) ⟩;
  exact Metric.tendsto_atTop.mpr h_squeeze

/-
**Main theorem for the greedy sequence**: A has natural density 1/2 and is pow2SumFree
-/
theorem main_greedy :
    pow2SumFree setA ∧
    Tendsto
      (fun N => ((((Icc 1 N).filter (fun m => m ∈ setA)).card : ℝ) / (N : ℝ)))
      atTop (nhds (1 / 2 : ℝ)) := by
  constructor
  · intro a ha b hb k
    exact sumFree (by simpa [setA] using ha) (by simpa [setA] using hb) k
  · simpa [countA, setA] using density_half

#print axioms main_greedy

end greedy
